SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 
CREATE PROCEDURE [api].[sp_UnMerge_GetParentChildData]  
	@ClientDB varchar(50) 
	, @Type VARCHAR(50) = 'Account' 
	, @GetChildren int 
	, @GUID AS VARCHAR(8000) 
as 
BEGIN 
 
	--DECLARE @ClientDb VARCHAR(50) = 'Raiders' 
 
	IF (SELECT @@VERSION) LIKE '%Azure%' 
		SET @ClientDB = '' 
	ELSE IF (SELECT @@VERSION) NOT LIKE '%Azure%' 
		SET @ClientDB = @ClientDB + '.' 
 
	-- API.[sp_UnMerge_GetParentChildData] 'Contact', 1, '7CACC40B-C43C-4007-9971-4986A713D88E' 
 
	-- Init 
	DECLARE  
		 @sql NVARCHAR(MAX) = '' 
		, @finalXml XML 
		--, @Type VARCHAR(50) = 'Account' 
		--, @GetChildren INT = 1 
		--, @GUID AS VARCHAR(8000) = '7CACC40B-C43C-4007-9971-4986A713D88E' 
 
	SET @sql = @sql 
	+ ' DECLARE @totalCount         INT' + CHAR(13) 
	+ ' DECLARE @xmlDataNode        XML' + CHAR(13) 
	+ ' DECLARE @rootNodeName       NVARCHAR(100)' + CHAR(13) 
	+ ' DECLARE @responseInfoNode   NVARCHAR(MAX)' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' DECLARE @baseData TABLE(' + CHAR(13) 
	+ ' 	Type		 VARCHAR(50),' + CHAR(13) 
	+ ' 	IsParent	 INT,' + CHAR(13) 
	+ ' 	GUID         VARCHAR(50),' + CHAR(13) 
	+ ' 	DataFound    BIT,' + CHAR(13) 
	+ ' 	Name         NVARCHAR(255),' + CHAR(13) 
	+ ' 	Address      NVARCHAR(2000),' + CHAR(13) 
	+ ' 	Email        NVARCHAR(500),' + CHAR(13) 
	+ ' 	Phone        NVARCHAR(255)' + CHAR(13) 
	+ ' 	----HyperLink    NVARCHAR(255),' + CHAR(13) 
	+ ' 	---IsDisabled	 BIT' + CHAR(13) 
	+ ' )' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' --DECLARE @GUIDCurrent INT' + CHAR(13) 
	+ ' ' + CHAR(13) 
 
	+ ' IF ''' + @Type + ''' = ''Account''' + CHAR(13) 
	+ ' BEGIN' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' 	INSERT INTO @baseData (Type, IsParent, GUID, DataFound, Name, Address, Email, Phone)' + CHAR(13) 
	+ ' 	SELECT ''' + @Type + ''' GUIDType' + CHAR(13) 
	+ ' 		, 1 IsParent' + CHAR(13) 
	+ ' 		, ''' + @GUID + '''' + CHAR(13) 
	+ ' 		, CASE WHEN LEN(isnull(b.SSB_CRMSYSTEM_CONTACTACCT_ID,'''')) = 0 THEN 0 ELSE 1 END DataFound' + CHAR(13) 
	+ ' 		, ISNULL(d.FirstName, '''') + '' '' + ISNULL(d.LastName, '''') Name ' + CHAR(13) 
	+ ' 		, d.AddressPrimaryStreet + '' '' + d.AddressPrimaryCity + '', '' + d.AddressPrimaryState + '' '' + d.AddressPrimaryZip Address' + CHAR(13) 
	+ ' 		, d.EmailPrimary Email' + CHAR(13) 
	+ ' 		, d.PhonePrimary Phone' + CHAR(13) 
	+ ' 		----, CASE WHEN b.id IS NOT NULL THEN ''https://na3.salesforce.com/'' + b.Id ELSE NULL END HyperLink' + CHAR(13) 
	+ ' 		----, 0 IsDisabled' + CHAR(13) 
	+ ' 	FROM ' + @ClientDB + 'dbo.dimcustomerssbid b' + CHAR(13) 
	+ ' 	LEFT JOIN ' + @ClientDB + 'mdm.compositerecord d ' + CHAR(13) 
	+ ' 	ON b.ssb_crmsystem_contact_id = d.ssb_crmsystem_contact_id' + CHAR(13) 
	+ ' 	where ssb_crmsystem_contactacct_id = ''' + @GUID + ''' and ssb_crmsystem_acct_primary_flag = 1' + CHAR(13) 
	+ ' ' + CHAR(13)	 
	+ ' ' + CHAR(13)	 
	+ ' ' + CHAR(13) 
	+ ' 	IF ' + CAST(@GetChildren AS VARCHAR(10)) + ' = 1' + CHAR(13) 
	+ ' 	BEGIN' + CHAR(13) 
	+ ' 		INSERT INTO @baseData (Type, IsParent, GUID, DataFound, Name, Address, Email, Phone)' + CHAR(13) 
	+ ' 		SELECT ''Contact'' GUIDType' + CHAR(13) 
	+ ' 			, 0 IsParent' + CHAR(13) 
	+ ' 			, b.SSB_CRMSYSTEM_Contact_ID' + CHAR(13) 
	+ ' 			, CASE WHEN LEN(isnull(d.SSB_CRMSYSTEM_CONTACT_ID,'''')) = 0 THEN 0 ELSE 1 END DataFound' + CHAR(13) 
	+ ' 			, ISNULL(d.FirstName,'''') + '' '' + ISNULL(d.LastName ,'''') Name ' + CHAR(13) 
	+ ' 			, d.AddressPrimaryStreet + '' '' + d.AddressPrimaryCity + '', '' + d.AddressPrimaryState + '' '' + d.AddressPrimaryZip Address' + CHAR(13) 
	+ ' 			, d.EmailPrimary Email' + CHAR(13) 
	+ ' 			, d.PhonePrimary Phone' + CHAR(13) 
	+ ' 			---, CASE WHEN b.id IS NOT NULL THEN ''https://na3.salesforce.com/'' + b.Id ELSE NULL END HyperLink' + CHAR(13) 
	+ ' 			---, 0 IsDisabled' + CHAR(13) 
	+ ' 	FROM ' + @ClientDB + 'dbo.dimcustomerssbid b' + CHAR(13) 
	+ ' 	Left JOIN ' + @ClientDB + 'mdm.compositerecord d ' + CHAR(13) 
	+ ' 	ON b.ssb_crmsystem_contact_id = d.ssb_crmsystem_contact_id' + CHAR(13) 
	+ ' 	where ssb_crmsystem_contactacct_id = ''' + @GUID + '''' + CHAR(13) 
	+ ' 	ORDER BY b.SSB_CRMSYSTEM_ACCT_PRIMARY_FLAG Desc' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' 	END' + CHAR(13) 
	+ ' END' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' IF ''' + @Type + ''' = ''Contact''' + CHAR(13) 
	+ ' BEGIN' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' 	INSERT INTO @baseData (Type, IsParent, GUID, DataFound, Name, Address, Email, Phone)' + CHAR(13) 
	+ ' 	SELECT ''' + @Type + ''' GUIDType' + CHAR(13) 
	+ ' 		, 1 IsParent' + CHAR(13) 
	+ ' 		, ''' + @GUID + '''' + CHAR(13) 
	+ ' 		, CASE WHEN LEN(isnull(d.SSB_CRMSYSTEM_CONTACT_ID,'''')) = 0 THEN 0 ELSE 1 END DataFound' + CHAR(13) 
	+ ' 			, ISNULL(d.FirstName,'''') + '' '' + ISNULL(d.LastName ,'''') Name ' + CHAR(13) 
	+ ' 			, d.AddressPrimaryStreet + '' '' + d.AddressPrimaryCity + '', '' + d.AddressPrimaryState + '' '' + d.AddressPrimaryZip Address' + CHAR(13) 
	+ ' 			, d.EmailPrimary Email' + CHAR(13) 
	+ ' 			, d.PhonePrimary Phone' + CHAR(13) 
	+ ' 		---, CASE WHEN b.id IS NOT NULL THEN ''https://na3.salesforce.com/'' + b.Id ELSE NULL END HyperLink' + CHAR(13) 
	+ ' 		---, 0 IsDisabled' + CHAR(13) 
	+ ' 	FROM ' + @ClientDB + 'dbo.dimcustomerssbid b' + CHAR(13) 
	+ ' 	Left JOIN ' + @ClientDB + 'mdm.compositerecord d ' + CHAR(13) 
	+ ' 	ON b.ssb_crmsystem_contact_id = d.ssb_crmsystem_contact_id' + CHAR(13) 
	+ ' 	where b.ssb_crmsystem_contact_id = ''' + @GUID + '''' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' 	IF ' + CAST(@GetChildren AS VARCHAR(10)) + ' = 1' + CHAR(13) 
	+ ' 	BEGIN' + CHAR(13) 
	+ ' 		INSERT INTO @baseData (Type, IsParent, GUID, DataFound, Name, Address, Email, Phone)' + CHAR(13) 
	+ ' 		SELECT ''CustomerRecord'' GUIDType' + CHAR(13) 
	+ ' 			, 0 IsParent' + CHAR(13) 
	+ ' 			,  d.SourceSystem  + '' - '' + d.SSID' + CHAR(13) 
	+ ' 			, 1 DataFound' + CHAR(13) 
	+ ' 			, COALESCE(ISNULL(d.FirstName,'''') + '' '' + ISNULL(d.LastName ,''''),NULL) Name ' + CHAR(13) 
	+ ' 			, COALESCE(d.AddressPrimaryStreet + '' '' + d.AddressPrimaryCity + '', '' + d.AddressPrimaryState + '' '' + d.AddressPrimaryZip, NULL) Address' + CHAR(13) 
	+ ' 			, COALESCE(d.EmailPrimary, NULL) Email' + CHAR(13) 
	+ ' 			, COALESCE(d.PhonePrimary, NULL) Phone' + CHAR(13) 
	+ ' 			---, NULL HyperLink' + CHAR(13) 
	+ ' 			----, 0 IsDisabled' + CHAR(13) 
	+ ' 		FROM ' + @ClientDB + 'dbo.dimcustomer  d' + CHAR(13) 
	+ ' 		inner join ' + @ClientDB + 'dbo.dimcustomerssbid b' + CHAR(13) 
	+ ' 		on d.dimcustomerid = b.dimcustomerid' + CHAR(13) 
	+ ' 			WHERE b.SSB_CRMSYSTEM_Contact_ID = ''' + @GUID + '''' + CHAR(13) 
	+ ' 	END' + CHAR(13) 
	+ ' END' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SELECT @totalCount = COUNT(*) FROM @baseData ' + CHAR(13) 
	+ ' IF @TotalCount = 0 ' + CHAR(13) 
	+ ' BEGIN' + CHAR(13) 
	+ ' 	INSERT INTO @baseData' + CHAR(13) 
	+ ' 	        ( Type' + CHAR(13) 
	+ ' 	        , IsParent' + CHAR(13) 
	+ ' 	        , GUID' + CHAR(13) 
	+ ' 	        , DataFound' + CHAR(13) 
	+ ' 	        )' + CHAR(13) 
	+ ' 	VALUES  ( ''' + @Type  + '''-- Type - varchar(50)' + CHAR(13) 
	+ ' 	        , 1  -- IsParent - int' + CHAR(13) 
	+ ' 	        , ''' + @GUID + '''  -- GUID - varchar(50)' + CHAR(13) 
	+ ' 	        , 0  -- DataFound - bit' + CHAR(13) 
	+ ' 	        )' + CHAR(13) 
	+ ' END' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' -- Set counts' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' UPDATE a' + CHAR(13) 
	+ ' SET Address = ''''' + CHAR(13) 
	+ ' FROM @baseData a' + CHAR(13) 
	+ ' WHERE LTRIM(Address) = '',%''' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SELECT @totalCount = COUNT(*) FROM @baseData  -- If paging were enabled, you wouldn''t count here' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' -- Create XML response data node' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SET @xmlDataNode = (SELECT' + CHAR(13) 
	+ ' 	Type, DataFound, GUID, ' + CHAR(13) 
	+ ' 	ISNULL(NULLIF(Name,'' ''),'''') AS Name, ' + CHAR(13) 
	+ ' 	ISNULL(NULLIF(Address, '' ''), '''') AS Address, ' + CHAR(13) 
	+ ' 	ISNULL(LTRIM(Email), '''') AS Email, ' + CHAR(13) 
	+ ' 	ISNULL(LTRIM(Phone), '''') AS Phone ' + CHAR(13) 
	+ ' 	----ISNULL(LTRIM(HyperLink), '''') AS HyperLink' + CHAR(13) 
	+ ' 	FROM @baseData' + CHAR(13) 
	+ ' 	FOR XML PATH (''Record''), ROOT(''Records''))' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SET @rootNodeName = ''Records''' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' -- Create response info node' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SET @responseInfoNode = (''<ResponseInfo>''' + CHAR(13) 
	+ ' 	+ ''<TotalCount>'' + CAST(@totalCount AS NVARCHAR(20)) + ''</TotalCount>''' + CHAR(13) 
	+ ' 	+ ''<RemainingCount>0</RemainingCount>''' + CHAR(13) 
	+ ' 	+ ''<RecordsInResponse>'' + CAST(@totalCount AS NVARCHAR(20)) + ''</RecordsInResponse>''' + CHAR(13) 
	+ ' 	+ ''<PagedResponse>false</PagedResponse>''' + CHAR(13) 
	+ ' 	+ ''<RowsPerPage></RowsPerPage>''' + CHAR(13) 
	+ ' 	+ ''<PageNumber></PageNumber>''' + CHAR(13) 
	+ ' 	+ ''<RootNodeName>'' + @rootNodeName + ''</RootNodeName>''' + CHAR(13) 
	+ ' 	+ ''</ResponseInfo>'')' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' -- Wrap response info and data, then return' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SET @finalXml = ''<Root>'' + @responseInfoNode + CAST(@xmlDataNode AS NVARCHAR(MAX)) + ''</Root>''' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' SELECT CAST(@finalXml AS XML)' + CHAR(13) 
	+ ' ' + CHAR(13) 
	+ ' --SELECT * FROM @baseData' + CHAR(13) 
	 
	--SELECT @sql 
 
	EXEC sp_executesql @sql, N'@finalXml XML OUTPUT', @finalXml OUTPUT 
 
END
GO
