SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [mdm].[Load_Master_DimCustomer_Deltas]
(
	@ClientDB VARCHAR(50)
)
AS
BEGIN
	 ----DECLARE @ClientDB VARCHAR(50) = 'MDM_CLIENT_DEV'

	IF (SELECT @@VERSION) LIKE '%Azure%'
	BEGIN
	SET @ClientDB = ''
	END
	ELSE
	BEGIN
	SET @ClientDB = @ClientDB + '.'
	END

	DECLARE 
		@sql NVARCHAR(MAX) = '' 
		, @return_code INT = 0
		, @PreSql NVARCHAR(MAX)  = ''
		, @JoinList NVARCHAR(MAX)  = ''
		, @ConditionList NVARCHAR(MAX)  = ''

	EXEC sp_executesql @sql
	SET @sql = ''
	
	SET @sql = 
		' IF NOT EXISTS (SELECT * FROM ' + @ClientDB + 'mdm.BusinessRules WHERE RuleType = ''Master Source VIP'' AND ISNULL(IsDeleted,0) = 0)' + CHAR(13)
		+ ' BEGIN' + CHAR(13)
		+ '		TRUNCATE TABLE ' + @ClientDB + 'dbo.Master_DimCustomer_Deltas' + CHAR(13)
		+ '		SET @return_code = -1' + CHAR(13)
		+ ' END' + CHAR(13)

	EXEC sp_executesql @sql, N'@return_code INT OUTPUT', @return_code = @return_code OUTPUT

	IF @return_code = -1
		RETURN

	SET @sql = ''
		+ 'Insert into '+ @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13) 
		+ 'values (current_timestamp, ''' + CONCAT(QUOTENAME(OBJECT_SCHEMA_NAME(@@PROCID)),'.',QUOTENAME(OBJECT_NAME(@@PROCID))) + ''', ''START'', 0);' + CHAR(13) + CHAR(13)

	SET @sql = ''
	--- Get all criteria pre-sql and run it

	SET @sql = @sql
		+ ' SELECT ' + CHAR(13)
		+ ' 	@PreSql = COALESCE(@PreSql + '' '', '''') + ISNULL(PreSQL, '''')' + CHAR(13)
		+ ' 	, @JoinList = COALESCE(@JoinList + '' '', '''') + ISNULL(CriteriaJoin, '''')' + CHAR(13)
		+ ' 	, @ConditionList = LTRIM(RTRIM(COALESCE(@ConditionList + '' '', '''') + ISNULL(CASE WHEN ISNULL(a.GroupID,0) = 0 THEN '''' ELSE ''GROUP'' + CAST(a.GroupID AS VARCHAR(5)) + ''START'' END + CASE WHEN ISNULL(a.LogicalOperator,'''') = '''' THEN ''AND '' ELSE a.LogicalOperator + '' '' END + b.CriteriaCondition + CASE WHEN ISNULL(a.GroupID,0) = 0 THEN '''' ELSE ''GROUP'' + CAST(a.GroupID AS VARCHAR(5)) + ''END'' END, ''''))) ' + CHAR(13)
		+ ' FROM ' + @ClientDB + 'mdm.BusinessRules a' + CHAR(13)
		+ ' INNER JOIN ' + @ClientDB + 'mdm.Criteria b ON a.CriteriaID = b.CriteriaID' + CHAR(13)
		+ ' WHERE 1=1' + CHAR(13)
		+ ' AND a.RuleType = ''Master Source VIP''' + CHAR(13)
		+ ' AND ISNULL(a.IsDeleted,0) = 0' + CHAR(13)
		+ ' ORDER BY a.LogicalOperator, priority' + CHAR(13) + CHAR(13)
		+ '' + CHAR(13)
		+ 'EXEC mdm.transformCriteriaConditionList @ConditionList, ''' + @ClientDB + ''', @ConditionList OUTPUT'

	----SELECT @sql
	EXEC sp_executesql @sql
			, N'@PreSql nvarchar(max) OUTPUT, @JoinList nvarchar(max) OUTPUT, @ConditionList nvarchar(max) OUTPUT'
		   ,  @PreSql OUTPUT, @JoinList OUTPUT, @ConditionList OUTPUT

	IF ISNULL(@PreSql,'') = ''
		SET @PreSql = 'RETURN'

 	-- Add TRY/CATCH block to force stoppage and log error      
	SET @PreSql = ''     
		+ ' BEGIN TRY' + CHAR(13)      
		+ @PreSql
		+ ' END TRY' + CHAR(13)     
		+ ' BEGIN CATCH' + CHAR(13)     
		+ '		DECLARE @ErrorMessage NVARCHAR(92)' + CHAR(13)     
		+ '			, @ErrorSeverity INT' + CHAR(13)     
		+ '			, @ErrorState INT' + CHAR(13) + CHAR(13)     
     
		+ '		SELECT @ErrorMessage = LEFT(ERROR_MESSAGE(), 92)' + CHAR(13)      
		+ '			, @ErrorSeverity = ERROR_SEVERITY()' + CHAR(13)      
		+ '			, @ErrorState = ERROR_STATE()' + CHAR(13) + CHAR(13)     
     
		+ '		INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)      
		+ '		VALUES (current_timestamp, ''' + CONCAT(QUOTENAME(OBJECT_SCHEMA_NAME(@@PROCID)),'.',QUOTENAME(OBJECT_NAME(@@PROCID))) + ''', ''ERROR - '' + @ErrorMessage + '''', 0);' + CHAR(13) + CHAR(13)     
     
		+ '		RAISERROR (@ErrorMessage, -- Message text.' + CHAR(13)     
		+ '             @ErrorSeverity, -- Severity.' + CHAR(13)     
		+ '             @ErrorState -- State.' + CHAR(13)     
		+ '             );' + CHAR(13)     
		+ ' END CATCH' + CHAR(13) + CHAR(13) 

	EXEC sp_executesql @PreSql

	----SELECT @PreSql, @JoinList, @ConditionList

	SET @sql = ''

	SET @sql = @sql
		+ ' IF OBJECT_ID(''tempdb..#deltas_delete'') IS NOT NULL' + CHAR(13)
		+ ' 	DROP TABLE #deltas_delete' + CHAR(13) + CHAR(13)

		+ ' SELECT DISTINCT a.ID' + CHAR(13)
		+ ' INTO #deltas_delete' + CHAR(13)
		+ ' FROM ' + @ClientDB + 'dbo.Master_DimCustomer_Deltas a' + CHAR(13)
		+ ' WHERE DATEDIFF(DAY,InsertDate,GETDATE()) > 7' + CHAR(13) + CHAR(13)

		+ ' CREATE CLUSTERED INDEX ix_deltas_delete_ID ON #deltas_delete (ID)' + CHAR(13) + CHAR(13)
		
		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Get stale deltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)

		+ ' IF (SELECT COUNT(0) FROM #deltas_delete) > 100000' + CHAR(13)
		+ ' BEGIN' + CHAR(13)
		+ ' 	EXEC ' + @ClientDB + 'dbo.sp_EnableDisableIndexes 0, ''dbo.Master_DimCustomer_Deltas''' + CHAR(13) + CHAR(13)

		+ '		INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ '		VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Disable indexes'', 0);' + CHAR(13)
		+ ' END' + CHAR(13) + CHAR(13)

		+ ' DELETE b' + CHAR(13)
		+ ' FROM #deltas_delete a' + CHAR(13)
		+ ' INNER JOIN ' + @ClientDB + 'dbo.Master_DimCustomer_Deltas b ON a.ID = b.ID' + CHAR(13) + CHAR(13)

		+ ' IF (SELECT COUNT(0) FROM #deltas_delete) > 100000' + CHAR(13)
		+ ' BEGIN' + CHAR(13)
		+ ' 	EXEC ' + @ClientDB + 'dbo.sp_EnableDisableIndexes 1, ''dbo.Master_DimCustomer_Deltas''' + CHAR(13) + CHAR(13)

		+ '		INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ '		VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Enable indexes'', 0);' + CHAR(13)
		+ ' END' + CHAR(13) + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)


	SET @sql = @sql
		+ ' SELECT *' + CHAR(13)
		+ ' INTO #masterDimCustDeltas' + CHAR(13)
		+ ' FROM ' + @ClientDB + 'dbo.vw_Master_DimCustomer_Deltas' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''#masterDimCustDeltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		+ ' CREATE TABLE #deltas (' + CHAR(13)
		+ ' 	DimCustomerId INT,' + CHAR(13)
		+ ' 	SSID NVARCHAR(100),' + CHAR(13)
		+ ' 	SourceSystem NVARCHAR(50),' + CHAR(13)
		+ ' 	Element NVARCHAR(50),' + CHAR(13)
		+ ' 	ElementID INT,' + CHAR(13)
		+ ' 	Field NVARCHAR(100),' + CHAR(13)
		+ ' 	FieldDisplay NVARCHAR(100),' + CHAR(13)
		+ ' 	Source NVARCHAR(500),' + CHAR(13)
		+ ' 	CD NVARCHAR(500),' + CHAR(13)
		+ ' 	CD_Status NVARCHAR(100),' + CHAR(13)
		+ ' 	Master NVARCHAR(500),' + CHAR(13)
		+ ' 	DisplayOrder INT' + CHAR(13)
		+ ' )' + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		+ ' CREATE CLUSTERED INDEX ix_masterdimcustdeltas_dimcustomerid ON #masterDimCustDeltas (DimCustomerId)' + CHAR(13)
		+ ' CREATE NONCLUSTERED INDEX ix_masterdimcustdeltas_ssis_sourcesystem ON #masterDimCustDeltas (SSID, SourceSystem)' + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)
	

	SET @sql = @sql
		+ ' INSERT INTO #deltas (DimCustomerId, SSID, SourceSystem, Element, FieldDisplay, Source, CD, CD_Status, Master, DisplayOrder)' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Name'' AS Element, ''Prefix'' AS FieldDisplay, a.s_Prefix AS Source, a.c_Prefix AS CD, a.NameIsCleanStatus as CD_Status' + CHAR(13)
		+ ' , a.m_Prefix AS Master, 1' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_Prefix,'''') != ISNULL(a.s_Prefix,'''') OR ISNULL(a.m_Prefix,'''') != ISNULL(a.c_Prefix,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Name'' AS Element, ''First Name'' AS FieldDisplay, a.s_FirstName AS Source, a.c_FirstName AS CD, a.NameIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_FirstName AS Master, 2' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_FirstName,'''') != ISNULL(a.s_FirstName,'''') OR ISNULL(a.m_FirstName,'''') != ISNULL(a.c_FirstName,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Name'' AS Element, ''Middle Name'' AS FieldDisplay, a.s_MiddleName AS Source, a.c_MiddleName AS CD, a.NameIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_MiddleName AS Master, 3' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_MiddleName,'''') != ISNULL(a.s_MiddleName,'''') OR ISNULL(a.m_MiddleName,'''') != ISNULL(a.c_MiddleName,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Name'' AS Element, ''Last Name'' AS FieldDisplay, a.s_LastName AS Source, a.c_LastName AS CD, a.NameIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_LastName AS Master, 4' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_LastName,'''') != ISNULL(a.s_LastName,'''') OR ISNULL(a.m_LastName,'''') != ISNULL(a.c_LastName,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Name'' AS Element, ''Suffix'' AS FieldDisplay, a.s_Suffix AS Source, a.c_Suffix AS CD, a.NameIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_Suffix AS Master, 5' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_Suffix,'''') != ISNULL(a.s_Suffix,'''') OR ISNULL(a.m_Suffix,'''') != ISNULL(a.c_Suffix,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Name'' AS Element, ''Full Name'' AS FieldDisplay, a.s_FullName AS Source, a.c_FullName AS CD, a.NameIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_FullName AS Master, 6' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_FullName,'''') != ISNULL(a.s_FullName,'''') OR ISNULL(a.m_FullName,'''') != ISNULL(a.c_FullName,''''))' + CHAR(13)
		+ ' ' + CHAR(13)

		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Company Name'' AS Element, ''Company Name'' AS FieldDisplay, a.s_CompanyName AS Source, a.c_CompanyName AS CD, a.CompanyNameIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_CompanyName AS Master, 7' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_CompanyName,'''') != ISNULL(a.s_CompanyName,'''') OR ISNULL(a.m_CompanyName,'''') != ISNULL(a.c_CompanyName,''''))' + CHAR(13)
		+ ' ' + CHAR(13)

		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary Street'' AS FieldDisplay, a.s_AddressPrimaryStreet AS Source, a.c_AddressPrimaryStreet AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimaryStreet AS Master, 8' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimaryStreet,'''') != ISNULL(a.s_AddressPrimaryStreet,'''') OR ISNULL(a.m_AddressPrimaryStreet,'''') != ISNULL(a.c_AddressPrimaryStreet,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary Suite'' AS FieldDisplay, a.s_AddressPrimarySuite AS Source, a.c_AddressPrimarySuite AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimarySuite AS Master, 9' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimarySuite,'''') != ISNULL(a.s_AddressPrimarySuite,'''') OR ISNULL(a.m_AddressPrimarySuite,'''') != ISNULL(a.c_AddressPrimarySuite,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary City'' AS FieldDisplay, a.s_AddressPrimaryCity AS Source, a.c_AddressPrimaryCity AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimaryCity AS Master, 10' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimaryCity,'''') != ISNULL(a.s_AddressPrimaryCity,'''') OR ISNULL(a.m_AddressPrimaryCity,'''') != ISNULL(a.c_AddressPrimaryCity,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary State'' AS FieldDisplay, a.s_AddressPrimaryState AS Source, a.c_AddressPrimaryState AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimaryState AS Master, 11' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimaryState,'''') != ISNULL(a.s_AddressPrimaryState,'''') OR ISNULL(a.m_AddressPrimaryState,'''') != ISNULL(a.c_AddressPrimaryState,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary Zip'' AS FieldDisplay, a.s_AddressPrimaryZip AS Source, a.c_AddressPrimaryZip AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimaryZip AS Master, 12' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimaryZip,'''') != ISNULL(a.s_AddressPrimaryZip,'''') OR ISNULL(a.m_AddressPrimaryZip,'''') != ISNULL(a.c_AddressPrimaryZip,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary County'' AS FieldDisplay, a.s_AddressPrimaryCounty AS Source, a.c_AddressPrimaryCounty AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimaryCounty AS Master, 13' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimaryCounty,'''') != ISNULL(a.s_AddressPrimaryCounty,'''') OR ISNULL(a.m_AddressPrimaryCounty,'''') != ISNULL(a.c_AddressPrimaryCounty,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Address'' AS Element, ''Address Primary Country'' AS FieldDisplay, a.s_AddressPrimaryCountry AS Source, a.c_AddressPrimaryCountry AS CD, a.AddressPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressPrimaryCountry AS Master, 14' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressPrimaryCountry,'''') != ISNULL(a.s_AddressPrimaryCountry,'''') OR ISNULL(a.m_AddressPrimaryCountry,'''') != ISNULL(a.c_AddressPrimaryCountry,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One Street'' AS FieldDisplay, a.s_AddressOneStreet AS Source, a.c_AddressOneStreet AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneStreet AS Master, 15' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneStreet,'''') != ISNULL(a.s_AddressOneStreet,'''') OR ISNULL(a.m_AddressOneStreet,'''') != ISNULL(a.c_AddressOneStreet,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One Suite'' AS FieldDisplay, a.s_AddressOneSuite AS Source, a.c_AddressOneSuite AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneSuite AS Master, 16' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneSuite,'''') != ISNULL(a.s_AddressOneSuite,'''') OR ISNULL(a.m_AddressOneSuite,'''') != ISNULL(a.c_AddressOneSuite,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One City'' AS FieldDisplay, a.s_AddressOneCity AS Source, a.c_AddressOneCity AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneCity AS Master, 17' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneCity,'''') != ISNULL(a.s_AddressOneCity,'''') OR ISNULL(a.m_AddressOneCity,'''') != ISNULL(a.c_AddressOneCity,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One State'' AS FieldDisplay, a.s_AddressOneState AS Source, a.c_AddressOneState AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneState AS Master, 18' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneState,'''') != ISNULL(a.s_AddressOneState,'''') OR ISNULL(a.m_AddressOneState,'''') != ISNULL(a.c_AddressOneState,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One Zip'' AS FieldDisplay, a.s_AddressOneZip AS Source, a.c_AddressOneZip AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneZip AS Master, 19' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneZip,'''') != ISNULL(a.s_AddressOneZip,'''') OR ISNULL(a.m_AddressOneZip,'''') != ISNULL(a.c_AddressOneZip,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One County'' AS FieldDisplay, a.s_AddressOneCounty AS Source, a.c_AddressOneCounty AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneCounty AS Master, 20' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneCounty,'''') != ISNULL(a.s_AddressOneCounty,'''') OR ISNULL(a.m_AddressOneCounty,'''') != ISNULL(a.c_AddressOneCounty,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address One'' AS Element, ''Address One Country'' AS FieldDisplay, a.s_AddressOneCountry AS Source, a.c_AddressOneCountry AS CD, a.AddressOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressOneCountry AS Master, 21' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressOneCountry,'''') != ISNULL(a.s_AddressOneCountry,'''') OR ISNULL(a.m_AddressOneCountry,'''') != ISNULL(a.c_AddressOneCountry,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two Street'' AS FieldDisplay, a.s_AddressTwoStreet AS Source, a.c_AddressTwoStreet AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoStreet AS Master, 22' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoStreet,'''') != ISNULL(a.s_AddressTwoStreet,'''') OR ISNULL(a.m_AddressTwoStreet,'''') != ISNULL(a.c_AddressTwoStreet,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two Suite'' AS FieldDisplay, a.s_AddressTwoSuite AS Source, a.c_AddressTwoSuite AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoSuite AS Master, 23' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoSuite,'''') != ISNULL(a.s_AddressTwoSuite,'''') OR ISNULL(a.m_AddressTwoSuite,'''') != ISNULL(a.c_AddressTwoSuite,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two City'' AS FieldDisplay, a.s_AddressTwoCity AS Source, a.c_AddressTwoCity AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoCity AS Master, 24' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoCity,'''') != ISNULL(a.s_AddressTwoCity,'''') OR ISNULL(a.m_AddressTwoCity,'''') != ISNULL(a.c_AddressTwoCity,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two State'' AS FieldDisplay, a.s_AddressTwoState AS Source, a.c_AddressTwoState AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoState AS Master, 25' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoState,'''') != ISNULL(a.s_AddressTwoState,'''') OR ISNULL(a.m_AddressTwoState,'''') != ISNULL(a.c_AddressTwoState,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two Zip'' AS FieldDisplay, a.s_AddressTwoZip AS Source, a.c_AddressTwoZip AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoZip AS Master, 26' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoZip,'''') != ISNULL(a.s_AddressTwoZip,'''') OR ISNULL(a.m_AddressTwoZip,'''') != ISNULL(a.c_AddressTwoZip,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two County'' AS FieldDisplay, a.s_AddressTwoCounty AS Source, a.c_AddressTwoCounty AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoCounty AS Master, 27' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoCounty,'''') != ISNULL(a.s_AddressTwoCounty,'''') OR ISNULL(a.m_AddressTwoCounty,'''') != ISNULL(a.c_AddressTwoCounty,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Two'' AS Element, ''Address Two Country'' AS FieldDisplay, a.s_AddressTwoCountry AS Source, a.c_AddressTwoCountry AS CD, a.AddressTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressTwoCountry AS Master, 28' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressTwoCountry,'''') != ISNULL(a.s_AddressTwoCountry,'''') OR ISNULL(a.m_AddressTwoCountry,'''') != ISNULL(a.c_AddressTwoCountry,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three Street'' AS FieldDisplay, a.s_AddressThreeStreet AS Source, a.c_AddressThreeStreet AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeStreet AS Master, 29' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeStreet,'''') != ISNULL(a.s_AddressThreeStreet,'''') OR ISNULL(a.m_AddressThreeStreet,'''') != ISNULL(a.c_AddressThreeStreet,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three Suite'' AS FieldDisplay, a.s_AddressThreeSuite AS Source, a.c_AddressThreeSuite AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeSuite AS Master, 30' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeSuite,'''') != ISNULL(a.s_AddressThreeSuite,'''') OR ISNULL(a.m_AddressThreeSuite,'''') != ISNULL(a.c_AddressThreeSuite,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three City'' AS FieldDisplay, a.s_AddressThreeCity AS Source, a.c_AddressThreeCity AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeCity AS Master, 31' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeCity,'''') != ISNULL(a.s_AddressThreeCity,'''') OR ISNULL(a.m_AddressThreeCity,'''') != ISNULL(a.c_AddressThreeCity,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three State'' AS FieldDisplay, a.s_AddressThreeState AS Source, a.c_AddressThreeState AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeState AS Master, 32' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeState,'''') != ISNULL(a.s_AddressThreeState,'''') OR ISNULL(a.m_AddressThreeState,'''') != ISNULL(a.c_AddressThreeState,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three Zip'' AS FieldDisplay, a.s_AddressThreeZip AS Source, a.c_AddressThreeZip AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeZip AS Master, 33' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeZip,'''') != ISNULL(a.s_AddressThreeZip,'''') OR ISNULL(a.m_AddressThreeZip,'''') != ISNULL(a.c_AddressThreeZip,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three County'' AS FieldDisplay, a.s_AddressThreeCounty AS Source, a.c_AddressThreeCounty AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeCounty AS Master, 34' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeCounty,'''') != ISNULL(a.s_AddressThreeCounty,'''') OR ISNULL(a.m_AddressThreeCounty,'''') != ISNULL(a.c_AddressThreeCounty,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Three'' AS Element, ''Address Three Country'' AS FieldDisplay, a.s_AddressThreeCountry AS Source, a.c_AddressThreeCountry AS CD, a.AddressThreeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressThreeCountry AS Master, 35' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressThreeCountry,'''') != ISNULL(a.s_AddressThreeCountry,'''') OR ISNULL(a.m_AddressThreeCountry,'''') != ISNULL(a.c_AddressThreeCountry,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four Street'' AS FieldDisplay, a.s_AddressFourStreet AS Source, a.c_AddressFourStreet AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourStreet AS Master, 36' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourStreet,'''') != ISNULL(a.s_AddressFourStreet,'''') OR ISNULL(a.m_AddressFourStreet,'''') != ISNULL(a.c_AddressFourStreet,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four Suite'' AS FieldDisplay, a.s_AddressFourSuite AS Source, a.c_AddressFourSuite AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourSuite AS Master, 37' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourSuite,'''') != ISNULL(a.s_AddressFourSuite,'''') OR ISNULL(a.m_AddressFourSuite,'''') != ISNULL(a.c_AddressFourSuite,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four City'' AS FieldDisplay, a.s_AddressFourCity AS Source, a.c_AddressFourCity AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourCity AS Master, 38' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourCity,'''') != ISNULL(a.s_AddressFourCity,'''') OR ISNULL(a.m_AddressFourCity,'''') != ISNULL(a.c_AddressFourCity,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four State'' AS FieldDisplay, a.s_AddressFourState AS Source, a.c_AddressFourState AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourState AS Master, 39' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourState,'''') != ISNULL(a.s_AddressFourState,'''') OR ISNULL(a.m_AddressFourState,'''') != ISNULL(a.c_AddressFourState,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four Zip'' AS FieldDisplay, a.s_AddressFourZip AS Source, a.c_AddressFourZip AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourZip AS Master, 40' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourZip,'''') != ISNULL(a.s_AddressFourZip,'''') OR ISNULL(a.m_AddressFourZip,'''') != ISNULL(a.c_AddressFourZip,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four County'' AS FieldDisplay, a.s_AddressFourCounty AS Source, a.c_AddressFourCounty AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourCounty AS Master, 41' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourCounty,'''') != ISNULL(a.s_AddressFourCounty,'''') OR ISNULL(a.m_AddressFourCounty,'''') != ISNULL(a.c_AddressFourCounty,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Address Four'' AS Element, ''Address Four Country'' AS FieldDisplay, a.s_AddressFourCountry AS Source, a.c_AddressFourCountry AS CD, a.AddressFourIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_AddressFourCountry AS Master, 42' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_AddressFourCountry,'''') != ISNULL(a.s_AddressFourCountry,'''') OR ISNULL(a.m_AddressFourCountry,'''') != ISNULL(a.c_AddressFourCountry,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Email'' AS Element, ''Email Primary'' AS FieldDisplay, a.s_EmailPrimary AS Source, a.c_EmailPrimary AS CD, a.EmailPrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_EmailPrimary AS Master, 43' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_EmailPrimary,'''') != ISNULL(a.s_EmailPrimary,'''') OR ISNULL(a.m_EmailPrimary,'''') != ISNULL(a.c_EmailPrimary,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Email One'' AS Element, ''Email One'' AS FieldDisplay, a.s_EmailOne AS Source, a.c_EmailOne AS CD, a.EmailOneIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_EmailOne AS Master, 44' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_EmailOne,'''') != ISNULL(a.s_EmailOne,'''') OR ISNULL(a.m_EmailOne,'''') != ISNULL(a.c_EmailOne,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Email Two'' AS Element, ''Email Two'' AS FieldDisplay, a.s_EmailTwo AS Source, a.c_EmailTwo AS CD, a.EmailTwoIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_EmailTwo AS Master, 45' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_EmailTwo,'''') != ISNULL(a.s_EmailTwo,'''') OR ISNULL(a.m_EmailTwo,'''') != ISNULL(a.c_EmailTwo,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Primary Phone'' AS Element, ''Phone Primary'' AS FieldDisplay, a.s_PhonePrimary AS Source, a.c_PhonePrimary AS CD, a.PhonePrimaryIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_PhonePrimary AS Master, 46' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_PhonePrimary,'''') != ISNULL(a.s_PhonePrimary,'''') OR ISNULL(a.m_PhonePrimary,'''') != ISNULL(a.c_PhonePrimary,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Phone Cell'' AS Element, ''Phone Cell'' AS FieldDisplay, a.s_PhoneCell AS Source, a.c_PhoneCell AS CD, a.PhoneCellIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_PhoneCell AS Master, 47' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_PhoneCell,'''') != ISNULL(a.s_PhoneCell,'''') OR ISNULL(a.m_PhoneCell,'''') != ISNULL(a.c_PhoneCell,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Phone Home'' AS Element, ''Phone Home'' AS FieldDisplay, a.s_PhoneHome AS Source, a.c_PhoneHome AS CD, a.PhoneHomeIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_PhoneHome AS Master, 48' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_PhoneHome,'''') != ISNULL(a.s_PhoneHome,'''') OR ISNULL(a.m_PhoneHome,'''') != ISNULL(a.c_PhoneHome,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Phone Business'' AS Element, ''Phone Business'' AS FieldDisplay, a.s_PhoneBusiness AS Source, a.c_PhoneBusiness AS CD, a.PhoneBusinessIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_PhoneBusiness AS Master, 49' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_PhoneBusiness,'''') != ISNULL(a.s_PhoneBusiness,'''') OR ISNULL(a.m_PhoneBusiness,'''') != ISNULL(a.c_PhoneBusiness,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Phone Fax'' AS Element, ''Phone Fax'' AS FieldDisplay, a.s_PhoneFax AS Source, a.c_PhoneFax AS CD, a.PhoneFaxIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_PhoneFax AS Master, 50' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_PhoneFax,'''') != ISNULL(a.s_PhoneFax,'''') OR ISNULL(a.m_PhoneFax,'''') != ISNULL(a.c_PhoneFax,''''))' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' UNION ALL' + CHAR(13)
		+ ' ' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, ''Phone Other'' AS Element, ''Phone Other'' AS FieldDisplay, a.s_PhoneOther AS Source, a.c_PhoneOther AS CD, a.PhoneOtherIsCleanStatus AS CD_Status' + CHAR(13)
		+ ' , a.m_PhoneOther AS Master, 51' + CHAR(13)
		+ ' FROM #masterDimCustDeltas a' + CHAR(13)
		+ ' WHERE 1=1 ' + CHAR(13)
		+ ' AND (ISNULL(a.m_PhoneOther,'''') != ISNULL(a.s_PhoneOther,'''') OR ISNULL(a.m_PhoneOther,'''') != ISNULL(a.c_PhoneOther,''''))' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''#deltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		+ ' CREATE CLUSTERED INDEX ix_deltas_dimcustomerid ON #deltas (DimCustomerId)' + CHAR(13)
		+ ' CREATE NONCLUSTERED INDEX ix_deltas_ssid_sourcesystem ON #deltas (SSID, SourceSystem)' + CHAR(13)
		+ ' CREATE NONCLUSTERED INDEX ix_deltas_displayorder ON #deltas (DisplayOrder)' + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		+ ' UPDATE a' + CHAR(13)
		+ ' SET a.ElementID = b.ElementID' + CHAR(13)
		+ '		,a.Field = REPLACE(a.FieldDisplay,'' '', '''')' + CHAR(13)
		+ ' FROM #deltas a' + CHAR(13)
		+ ' INNER JOIN ' + @ClientDB + 'mdm.Element b ON a.Element = b.Element' + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		--+ ' --SELECT a.DimCustomerId, SSID, SourceSystem, Element, a.ElementID, a.Field, FieldDisplay, Source, CD, CD_Status, Master' + CHAR(13)
		+ ' DELETE a' + CHAR(13)
		+ ' FROM #deltas a' + CHAR(13)
		+ ' LEFT JOIN ' + @ClientDB + 'mdm.overrides b ON a.DimCustomerId = b.DimCustomerId' + CHAR(13)
		+ '		AND a.Field = b.Field' + CHAR(13)
		+ ' WHERE 1=1' + CHAR(13)
		+ ' AND b.OverrideID IS NOT NULL' + CHAR(13)
		+ ' AND ISNULL(a.Master,'''') = ISNULL(b.Value,'''')' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Delete overrides from #deltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)
	
	SET @sql = @sql	
		+ ' DELETE a' + CHAR(13)
		+ ' FROM #deltas a' + CHAR(13)
		+ ' LEFT JOIN ' + @ClientDB + 'dbo.Master_DimCustomer_Deltas b ON a.DimCustomerId = b.DimCustomerId' + CHAR(13)
		+ '		AND a.Field = b.Field' + CHAR(13)
		+ '		AND ISNULL(a.Master,'''') = ISNULL(b.Master,'''')' + CHAR(13)
		+ ' --LEFT JOIN ' + @ClientDB + 'mdm.overrides c ON a.DimCustomerId = c.DimCustomerId' + CHAR(13)
		+ ' --		AND a.Field = c.Field' + CHAR(13)
		+ ' WHERE 1=1' + CHAR(13)
		+ ' --AND (b.ProcessedDate IS NOT NULL' + CHAR(13)
		+ ' --AND ISNULL(a.Master,'''') = ISNULL(c.Value,''''))' + CHAR(13)
		+ ' AND b.ProcessedDate IS NOT NULL' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Delete previously processed from #deltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		+ ' DELETE b' + CHAR(13)
		+ ' FROM #deltas a' + CHAR(13)
		+ ' INNER JOIN ' + @ClientDB + 'dbo.Master_DimCustomer_Deltas b ON a.DimCustomerId = b.DimCustomerId' + CHAR(13)
		+ ' WHERE 1=1' + CHAR(13)
		+ ' AND b.ProcessedDate IS NULL' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Delete matching/unprocessed from dbo.Master_DimCustomer_Deltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)
	SET @sql = @sql + CHAR(13) + CHAR(13)

	SET @sql = @sql
		+ ' IF (SELECT COUNT(0) FROM #deltas) > 100000' + CHAR(13)
		+ ' BEGIN' + CHAR(13)
		+ ' 	EXEC ' + @ClientDB + 'dbo.sp_EnableDisableIndexes 0, ''dbo.Master_DimCustomer_Deltas''' + CHAR(13) + CHAR(13)

		+ '		INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ '		VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Disable indexes'', 0);' + CHAR(13)
		+ ' END' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'dbo.Master_DimCustomer_Deltas (DimCustomerId, SSID, SourceSystem, Element, ElementID, Field, FieldDisplay, Source, CD, CD_Status, Master, DisplayOrder, AcceptedBy, AcceptedDate, ProcessedDate)' + CHAR(13)
		+ ' SELECT a.DimCustomerId, a.SSID, a.SourceSystem, a.Element, a.ElementID, a.Field, a.FieldDisplay, a.Source, a.CD, a.CD_Status, a.Master, a.DisplayOrder, CAST(NULL AS VARCHAR(25)) AS AcceptedBy, CAST(NULL AS DATETIME) AS AcceptedDate, CAST(NULL AS DATETIME) AS ProcessedDate' + CHAR(13)
		+ ' FROM #deltas a' + CHAR(13)
	
	
	IF ISNULL(@JoinList,'') != '' OR ISNULL(@ConditionList,'') != ''
	BEGIN
		SET @sql = @sql 
			+ ' INNER JOIN ' + @ClientDB + 'dbo.DimCustomer dimcust ON a.DimCustomerId = dimcust.DimCustomerId' + CHAR(13)
		
		IF ISNULL(@JoinList,'') != ''
			SET @sql = @sql + @JoinList + CHAR(13)
		
		IF ISNULL(@ConditionList,'') != ''
			SET @sql = @sql
				+ ' WHERE 1=1' + CHAR(13)
				+ ' AND (' + CHAR(13)
					+ @ConditionList + CHAR(13)
				+ ')' + CHAR(13)
	END

	SET @sql = @sql + ' ORDER BY a.SSID, a.SourceSystem, a.DisplayOrder' + CHAR(13) + CHAR(13)

		+ ' INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ ' VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Load dbo.Master_DimCustomer_Deltas'', @@ROWCOUNT);' + CHAR(13) + CHAR(13)

		+ ' IF (SELECT COUNT(0) FROM #deltas) > 100000' + CHAR(13)
		+ ' BEGIN' + CHAR(13)
		+ ' 	EXEC ' + @ClientDB + 'dbo.sp_EnableDisableIndexes 1, ''dbo.Master_DimCustomer_Deltas''' + CHAR(13) + CHAR(13)

		+ '		INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)
		+ '		VALUES (current_timestamp, ''Load_Master_DimCustomer_Deltas'', ''Enable indexes'', 0);' + CHAR(13)
		+ ' END' + CHAR(13) + CHAR(13)

 	-- Add TRY/CATCH block to force stoppage and log error      
	SET @sql = ''     
		+ ' BEGIN TRY' + CHAR(13)      
		+ @sql
		+ ' END TRY' + CHAR(13)     
		+ ' BEGIN CATCH' + CHAR(13)     
		+ '		DECLARE @ErrorMessage NVARCHAR(92)' + CHAR(13)     
		+ '			, @ErrorSeverity INT' + CHAR(13)     
		+ '			, @ErrorState INT' + CHAR(13) + CHAR(13)     
     
		+ '		SELECT @ErrorMessage = LEFT(ERROR_MESSAGE(), 92)' + CHAR(13)      
		+ '			, @ErrorSeverity = ERROR_SEVERITY()' + CHAR(13)      
		+ '			, @ErrorState = ERROR_STATE()' + CHAR(13) + CHAR(13)     
     
		+ '		INSERT INTO ' + @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13)      
		+ '		VALUES (current_timestamp, ''' + CONCAT(QUOTENAME(OBJECT_SCHEMA_NAME(@@PROCID)),'.',QUOTENAME(OBJECT_NAME(@@PROCID))) + ''', ''ERROR - '' + @ErrorMessage + '''', 0);' + CHAR(13) + CHAR(13)     
     
		+ '		RAISERROR (@ErrorMessage, -- Message text.' + CHAR(13)     
		+ '             @ErrorSeverity, -- Severity.' + CHAR(13)     
		+ '             @ErrorState -- State.' + CHAR(13)     
		+ '             );' + CHAR(13)     
		+ ' END CATCH' + CHAR(13) + CHAR(13) 

	----SELECT @sql	

	EXEC sp_executesql @sql

	SET @sql = ''
		+ 'Insert into '+ @ClientDB + 'mdm.auditlog (logdate, mdm_process, process_step, cnt)' + CHAR(13) 
		+ 'values (current_timestamp, ''' + CONCAT(QUOTENAME(OBJECT_SCHEMA_NAME(@@PROCID)),'.',QUOTENAME(OBJECT_NAME(@@PROCID))) + ''', ''END'', 0);' + CHAR(13) + CHAR(13)

	EXEC sp_executesql @sql
END
GO
