CREATE TABLE [amy].[zzathcontact_old0310]
(
[id] [nvarchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (68) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[street1] [nvarchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[street2] [nvarchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_date] [datetime] NULL,
[creation_source] [nvarchar] (59) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[promotion_cnt] [int] NULL,
[promo_opt_in] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[macid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorInterest] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketsInterest] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KidsInterest] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MilitaryInterest] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[auction_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionUserName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionLastLogin] [nvarchar] (52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionTotalBids] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuctionCnt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TMFInd] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSInd] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketingInd] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineAuctionInd] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TMFSetupDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSSetupDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketSetupDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineAuctionSetupDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorAccountName] [nvarchar] (61) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorStatus] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorLifetimeGiving] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorPriorityPoints] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorPPRank] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSBirthDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSBidCnt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSBidWins] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSListingCnt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketAccountNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TK] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SC] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shop_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shop_ind] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shop_order_count] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fullname] [nvarchar] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fsaccount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VB] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contacttypeid] [nvarchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SW] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EQ] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[classyear] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GF] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[student_ind] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
