CREATE TABLE [amy].[zz_raw_patron_list03122018 ]
(
[ContactID] [int] NULL,
[ADNumber] [int] NULL,
[SetupDate] [datetime] NULL,
[Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountName] [nvarchar] (74) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInitial] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (174) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (93) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHHome] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHBusiness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ext] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHOther1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHOther1Desc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHOther2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHOther2Desc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketNumber] [int] NULL,
[TicketName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlumniInfo] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseName] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseBirthday] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseAlumniInfo] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChildrenNames] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CashBasisPP] [decimal] (28, 10) NULL,
[AccrualBasisPP] [decimal] (28, 10) NULL,
[AdjustedPP] [decimal] (28, 15) NULL,
[LastEdited] [datetime] NULL,
[EditedBy] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramName] [nvarchar] (158) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dear] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessTitle] [nvarchar] (68) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankCity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoutingNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LifetimeGiving] [decimal] (28, 10) NULL,
[UDF1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UDF2] [nvarchar] (151) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UDF3] [nvarchar] (166) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UDF4] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UDF5] [nvarchar] (158) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCycle] [int] NULL,
[EStatement] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FundraiserID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LinkedAccount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fundraiser] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActionNotes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StaffAssigned] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingMonth] [int] NULL,
[PPRank] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PledgeLevel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OverrideLevel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceiptsLevel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CumulativePriority] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImageLink] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PinNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
