CREATE TABLE [amy].[zz_parkingFBbk06152018_axs]
(
[accountnumber] [nvarchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[categoryname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventlookupid] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventtitleshort] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventid] [numeric] (10, 0) NULL,
[year] [int] NULL,
[seatpricecode] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatsection] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatrow] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatseat] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatid] [int] NULL,
[tixsyspricecode] [numeric] (10, 0) NULL,
[paid] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[sent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[paidpercent] [numeric] (38, 19) NULL,
[schpercent] [numeric] (38, 19) NULL,
[ordergroupbottomlinegrandtotal] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentsonhold] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentscleared] [numeric] (19, 4) NULL,
[update_date] [datetime] NOT NULL,
[tixseatlastupdate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_date] [datetime] NULL,
[cancel_ind] [bit] NULL,
[cancel_date] [datetime] NULL,
[seatdetail_individual_history_id] [int] NOT NULL IDENTITY(1, 1),
[CAPTERMSTARTDATE] [datetime] NULL,
[CAPTERMSTARTYEAR] [int] NULL,
[CAP_Percent_Owe_ToDate] [numeric] (10, 2) NULL,
[lineal_transfer_release_ind] [bit] NULL,
[lineal_transfer_received_ind] [bit] NULL,
[lineal_transfer_date] [datetime] NULL,
[lineal_transfer_parent] [int] NULL,
[ticket_start_date] [datetime] NULL,
[ticket_start_year] [int] NULL,
[lineal_transfer_parent_acct] [int] NULL,
[relocation_release_ind] [bit] NULL,
[relocation_start_ind] [bit] NULL,
[relocation_date] [datetime] NULL,
[relocation_parent_id] [int] NULL,
[seatareaid] [int] NULL,
[seatregionid] [int] NULL,
[SeatTerm] [int] NULL,
[ordernumber] [numeric] (10, 0) NULL,
[seatlastupdated] [datetime] NULL,
[renewal_date] [date] NULL,
[renewal_order] [bit] NULL,
[ordergroupdate] [datetime2] (6) NULL,
[ordergrouplastupdated] [datetime2] (6) NULL,
[renewal_ticket] [bit] NULL,
[new_ticket] [bit] NULL,
[creditamount] [money] NULL,
[ticketvalue] [numeric] (19, 4) NULL,
[ticketpaid] [numeric] (19, 4) NULL,
[tixseatgroupid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgrouppricelevel] [numeric] (10, 0) NULL,
[tixseatofferid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addonticket] [bit] NULL,
[min_ticketpaymentdate] [date] NULL,
[renewal_complete] [int] NULL,
[annualpaidperseat] [money] NULL,
[scheduledpaidperseat] [money] NULL,
[totalpaidperseat] [money] NULL,
[annualpaidpercent] [numeric] (18, 0) NULL,
[annualscheduledpercent] [numeric] (18, 0) NULL,
[pacseason] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pacitem] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[i_pl] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seq] [int] NULL
)
GO
