CREATE TABLE [amy].[ticketterms]
(
[term] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[adnumber] [int] NULL,
[ADA] [int] NULL,
[E] [int] NULL,
[EC] [int] NULL,
[ZC E] [int] NULL,
[Lettermen] [int] NULL,
[FacultyAD] [int] NULL,
[Faculty] [int] NULL,
[DC] [int] NULL,
[Comp] [int] NULL,
[Donor] [int] NULL,
[iseason] [int] NULL,
[uo] [int] NULL,
[UO-R] [int] NULL,
[SingleSeason] [int] NULL,
[Suite] [int] NULL,
[Suite SRO] [int] NULL,
[DS SRO Inventory] [int] NULL,
[ordernumber] [int] NULL,
[Seat Sold Date] [datetime] NULL,
[orderdate] [datetime] NULL,
[SeatingArea] [nvarchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeatAreaID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[neighborhood] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[section] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[row] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seat] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticketcount] [int] NULL,
[CAP_Amount] [decimal] (28, 10) NULL,
[Annual_amount] [decimal] (28, 10) NULL
)
GO
