CREATE TABLE [amy].[zz_patron_round2_04202018_finallist]
(
[acct] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountname] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[countrycode] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usecase] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[homephone] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[businessphone] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousefirstname] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spouselastname] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousebirthday] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PublishName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MGStatus] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donortype] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustType] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DonorStatus] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustStatus] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StaffAssigned] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlumnInfo] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrefClassYear] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseAlumniInfo] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpousePrefClassYear] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_A] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[countrycode_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usecase_A] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatronStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OrgType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrgName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingName_A] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
