CREATE TABLE [amy].[tbl_renewal_product]
(
[id] [int] NULL,
[renewal_id] [int] NULL,
[product_type] [nvarchar] (52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Screen] [nvarchar] (52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [nvarchar] (89) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[descr] [nvarchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[price] [decimal] (28, 10) NULL,
[donation] [decimal] (28, 10) NULL,
[max_qty] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ada_ind] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sort_order] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comments_ind] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_event] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_event_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_offer_code] [nvarchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_offer_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_price_code] [nvarchar] (57) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_pricecode_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_price_level] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_pricelevel_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_group_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_seatgroup_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_zone_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_statuscode_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_deliverymethod_code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_deliverymethod_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_deliverymethod_code_alt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_deliverymethod_id_alt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_fee_code] [nvarchar] (59) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_fee_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[update_date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment] [nvarchar] (86) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addl_info_req_ind] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addl_info_req_type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addl_info_req_text] [nvarchar] (101) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comment_prefix] [nvarchar] (54) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donation_programid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
