CREATE TABLE [amy].[wealthengine]
(
[WE Run ID] [bigint] NULL,
[WE Record ID] [bigint] NULL,
[originalID] [int] NULL,
[originalID2] [int] NULL,
[Search Date] [datetime] NULL,
[Prefix] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address12and3] [nvarchar] (86) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [int] NULL,
[2nd Person Last Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Person First Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[2nd Person Middle Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client supplied business phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business name 2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client supplied business phone 2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business name 3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client supplied business phone 3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Giving] [decimal] (28, 10) NULL,
[Number of Gifts] [int] NULL,
[First Gift Date] [date] NULL,
[First Gift Amount] [decimal] (28, 10) NULL,
[Last Gift Date] [date] NULL,
[Last Gift Amount] [decimal] (28, 10) NULL,
[Largest Gift Date] [date] NULL,
[Largest Gift Amount] [decimal] (28, 10) NULL,
[Client supplied Age] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client supplied Birthday] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client Supplied Graduation Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date of Birth] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P2G Score Combo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P2G Description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P2G Score (first digit)] [int] NULL,
[P2G Score (second digit)] [int] NULL,
[Total Assets] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Asset Rating] [int] NULL,
[Net Worth] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Net Worth Rating] [int] NULL,
[Cash on Hand] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cash on Hand Rating] [int] NULL,
[Estimated Annual Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Estimated Annual Donation Rating] [int] NULL,
[Gift Capacity Range] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift Capacity Rating] [int] NULL,
[Gift Capacity - Income] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift Capacity - Real Estate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift Capacity - Stock] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift Capacity - Pension] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gift Capacity - Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Estimated Gift Capacity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Influence Rating] [int] NULL,
[Inclination: Affiliation] [nvarchar] (79) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inclination: Giving] [nvarchar] (66) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bequest] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Annuity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Trust] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income Rating] [int] NULL,
[Pension] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pension Rating] [int] NULL,
[Real Estate Value] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Real Estate Value Rating] [int] NULL,
[Real Estate Properties] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stock Direct Holdings] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stock Direct Holdings Rating] [int] NULL,
[Stock Total Value] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stock Total Value Rating] [int] NULL,
[Charitable Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Charitable Donations Rating] [int] NULL,
[Political Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Political Donations Rating] [int] NULL,
[Total Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total Donations Rating] [int] NULL,
[Business Ownership] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Co. Ownership Value Rating] [int] NULL,
[Co. Sales Volume] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Co. Sales Volume Rating] [int] NULL,
[RFM Total] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFM - Recency] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFM - Frequency] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RFM - Money] [int] NULL,
[Aircraft Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boat Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Children] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inner Circle Match] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inner Circle Member] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Major Donor Member] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Board Member] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Match Count] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Folder Name] [nvarchar] (72) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Aircraft] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Airmen] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - D&B] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - D&B State Biz Reg] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Vols & Dirs] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Do Not Mail] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Charitable Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Fed Election Campaign] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - GuideStar Foundation] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - GuideStar Directors] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Household Profile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Hoovers] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Major Donor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Physicians Profile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Market Guide] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - IRS Section 527 Directors] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - IRS Section 527 Political Org] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Pension] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Philanthropic Donations] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Real Estate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - State Political] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - SSA Death Index] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM - Wealth ID Securities] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM -- Foundation Trustees] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM -- Merchant Vessels] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QOM -- Marquis Whos Who] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 6] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 7] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 8] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 9] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 10] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 11] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 12] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 13] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 14] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute 15] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Major Gift Model Decile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Major Gift Model Score] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Annual Fund Model Decile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Annual Fund Model Score] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Planned Giving Model Decile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Planned Giving Model Score] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Likelihood to Give Model Decile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Likelihood to Give Model Score] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next Ask Amount Model Decile] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next Ask Amount Model Score] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cluster Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deceased Indicator] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T1] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T2] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
CREATE NONCLUSTERED INDEX [nci_wi_wealthengine_26ABAA7D359BF03970E03D8C9F57544A] ON [amy].[wealthengine] ([originalID]) INCLUDE ([Gift Capacity Range], [Net Worth], [P2G Description], [P2G Score Combo])
GO
CREATE NONCLUSTERED INDEX [wealthengine_accountnumber_ind01] ON [amy].[wealthengine] ([originalID2], [originalID])
GO
