CREATE TABLE [amy].[zz_rpt_seatrecon_tb_test_pac]
(
[adnumber] [int] NULL,
[accountname] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[sporttype] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticket Total] [int] NULL,
[CAP] [decimal] (38, 4) NOT NULL,
[Annual] [decimal] (38, 4) NOT NULL,
[CAPCredit] [decimal] (38, 4) NULL,
[AnnualCredit] [decimal] (38, 4) NULL,
[Advantage Adjusted CAP Pledge] [money] NOT NULL,
[Adv CAP Pledge] [money] NOT NULL,
[Adv CAP Receipt AMount] [money] NOT NULL,
[Adv CAP Match Pledge] [money] NOT NULL,
[Adv CAP Match Receipt] [money] NOT NULL,
[Adv CAP Credit] [money] NOT NULL,
[Advantage Adjusted Annual Pledge] [money] NOT NULL,
[Adv Annual  Pledge] [money] NOT NULL,
[Adv Annual Receipt] [money] NOT NULL,
[Adv Annual Match Pledge] [money] NOT NULL,
[Adv Annual Match Receipt] [money] NOT NULL,
[Adv Annual Credit] [money] NOT NULL,
[scheduledpayments] [money] NULL,
[capital_ada_credit_amount] [money] NULL,
[ticketpaidpercent] [numeric] (38, 19) NULL,
[ticketscheduledpercent] [numeric] (38, 19) NULL,
[capdifference] [decimal] (38, 4) NULL,
[annualdifference] [decimal] (38, 4) NULL,
[caprecdifference] [decimal] (38, 4) NULL,
[annualrecdifference] [decimal] (38, 4) NULL,
[ADA] [int] NULL,
[E] [int] NULL,
[EC] [int] NULL,
[ZC E] [int] NULL,
[Lettermen] [int] NULL,
[FacultyAD] [int] NULL,
[Faculty] [int] NULL,
[DC] [int] NULL,
[Comp] [int] NULL,
[UO] [int] NULL,
[UO-R] [int] NULL,
[SingleSeason] [int] NULL,
[Ticket Count] [int] NULL,
[ALL_TICKETS] [int] NULL,
[AnnualScheduledPayments] [money] NULL,
[KFCScheduledPayments] [money] NULL,
[min_annual_receipt_date] [datetime] NULL,
[Ticketyear] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TixEventLookupID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[updatedate] [datetime] NOT NULL,
[cap_20] [int] NULL,
[CAP_40] [int] NULL,
[CAP_60] [int] NULL,
[CAP_80] [int] NULL,
[CAP_100] [int] NULL,
[CAP_OTHER] [int] NULL,
[CAP_DUE] [numeric] (38, 6) NOT NULL,
[LinealTransfer] [int] NULL,
[CapStillDue] [numeric] (38, 6) NULL,
[ordernumber] [numeric] (10, 0) NULL,
[seatlastupdated] [datetime] NULL,
[lastupdated] [datetime] NOT NULL,
[ordergroupbottomlinegrandtotal] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentscleared] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentsonhold] [numeric] (19, 4) NULL,
[vtxcusttype] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[email] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[renewal_date] [date] NULL,
[newtickets] [int] NULL,
[min_ticketpaymentdate] [date] NULL,
[pacseason] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pacitem] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
