CREATE TABLE [amy].[FBCAP2015]
(
[percentdue] [decimal] (28, 10) NULL,
[adnumber] [int] NULL,
[accountname] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatregionname] [nvarchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatregionid] [int] NULL,
[cap_amount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[annual_amount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticket Total] [int] NULL,
[CAP] [decimal] (28, 10) NULL,
[Annual] [decimal] (28, 10) NULL,
[CAPCredit] [decimal] (28, 10) NULL,
[AnnualCredit] [decimal] (28, 10) NULL,
[Advantage Adjusted CAP Pledge] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv CAP Pledge] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv CAP Receipt AMount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv CAP Match Pledge] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv CAP Match Receipt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv CAP Credit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Advantage Adjusted Annual Pledge] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv Annual  Pledge] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv Annual Receipt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv Annual Match Pledge] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv Annual Match Receipt] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adv Annual Credit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADA] [int] NULL,
[E] [int] NULL,
[EC] [int] NULL,
[ZC E] [int] NULL,
[Lettermen] [int] NULL,
[FacultyAD] [int] NULL,
[Faculty] [int] NULL,
[DC] [int] NULL,
[Comp] [int] NULL,
[UO] [int] NULL,
[UO-R] [int] NULL,
[SingleSeason] [int] NULL,
[Ticket Count] [int] NULL,
[capdifference] [decimal] (28, 10) NULL,
[annualdifference] [decimal] (28, 10) NULL,
[caprecdifference] [decimal] (28, 10) NULL,
[annualrecdifference] [decimal] (28, 10) NULL
)
GO
