CREATE TABLE [dbo].[ADVEvents_tbl_order]
(
[id] [int] NOT NULL,
[sessionid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_date] [datetime] NULL,
[submit_date] [datetime] NULL,
[processor] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_date] [datetime] NULL,
[va_order_id] [int] NULL,
[acct] [bigint] NULL,
[name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_addr] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_addr2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_city] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_state] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_zip] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pmt_schedule] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[card_number] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[card_expire] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_addr] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_addr2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_city] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_state] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_zip] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_email] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_pmt_schedule] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_card_number] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[don_card_expire] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[faculty_info] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mail_care_of] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alumni_info] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home_phone] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[work_phone] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cell_phone] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[title] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_number] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[check_name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trans_profile_id] [int] NULL,
[don_post_date] [datetime] NULL,
[lettermen_info] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delivery_method] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[trans_post_date] [datetime] NULL,
[pmt_method] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[va_rg_date] [datetime] NULL,
[va_rg_order_id] [int] NULL,
[uin] [int] NULL,
[card_id] [int] NULL,
[ticket_trans_profile_id] [int] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE NONCLUSTERED INDEX [nci_wi_ADVEvents_tbl_order_4BF42347B3A84FDB002684694EF754CB] ON [dbo].[ADVEvents_tbl_order] ([category], [id], [submit_date]) INCLUDE ([acct])
GO
