CREATE TABLE [dbo].[zip_codes_database]
(
[ZipCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryRecord] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Population] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseholdsPerZipCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WhitePopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BlackPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HispanicPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AsianPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HawaiianPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IndianPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MalePopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FemalePopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonsPerHousehold] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AverageHouseValue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncomePerHousehold] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedianAge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedianAgeMale] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedianAgeFemale] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Longitude] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Elevation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateFullName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasAbbreviation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AreaCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountyFIPS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateFIPS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TimeZone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DayLightSaving] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSA_Div] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSA_Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSA_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MSA_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMSA_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Region] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Division] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfBusinesses] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfEmployees] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessFirstQuarterPayroll] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessAnnualPayroll] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessEmploymentFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrowthRank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrowingCountiesA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrowingCountiesB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrowthIncreaseNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GrowthIncreasePercentage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSAPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSADivisionPopulation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CongressionalDistrict] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CongressionalLandArea] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryResidential] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryBusiness] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeliveryTotal] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLastLineKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassificationCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MultiCounty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSAName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CBSA_Div_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityStateKey] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PopulationEstimate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LandArea] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WaterArea] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityMixedCase] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityAliasMixedCase] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoxCount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SFDU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MFDU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateANSI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CountyANSI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPIntroDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AliasIntroDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CityDeliveryIndicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierRouteRateSortation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FinanceNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UniqueZIPName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSAStateCountyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareCBSACode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareCBSAName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareCBSAType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarketRatingAreaID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
WITH
(
DATA_COMPRESSION = PAGE
)
GO
CREATE CLUSTERED INDEX [CIX_dbo_zip_codes_database_ZipCode] ON [dbo].[zip_codes_database] ([ZipCode]) WITH (DATA_COMPRESSION = PAGE)
GO
