CREATE TABLE [ods].[PAC_TouchPoint]
(
[AccountDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[AccountID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TouchPointID] [uniqueidentifier] NOT NULL,
[OwnerID] [bigint] NULL,
[OwnerFirstName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerMiddleName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerLastName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorityID] [int] NULL,
[ContactName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttachmentID] [uniqueidentifier] NULL,
[AttachmentFileName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DueDate] [date] NULL,
[IsAllDay] [bit] NULL,
[IsPrivate] [bit] NULL,
[MeetingStartTime] [date] NULL,
[MeetingEndTime] [date] NULL,
[StatusCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TypeCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TypeCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TypeCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TypeCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[WayToContact] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WayToContactCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[WayToContactCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[WayToContactCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[WayToContactCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[OriginationUserID] [bigint] NULL,
[OriginationTime] [datetime] NULL,
[sys_CreateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_CreateTS] [datetime] NULL,
[sys_CreateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_Status] [int] NULL,
[sys_UpdateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_UpdateTS] [datetime] NULL,
[sys_UpdateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__PAC_TouchPoint] ON [ods].[PAC_TouchPoint]
GO
