CREATE TABLE [ods].[PAC_PacTran]
(
[OrganizationID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PacTranID] [bigint] NOT NULL,
[AccountDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APIMethod] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChannelID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ClientID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ClientIPAddr] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comments] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ControlID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ExchInTranID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ExchOutTranID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LocationID] [uniqueidentifier] NULL,
[PacBatchID] [bigint] NULL,
[PaymentAmt] [money] NULL,
[Reference] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceURL] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefundAmt] [money] NULL,
[RequestURI] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevenueRecogAmt] [money] NULL,
[SourceCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TerminalID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TransferFromTranID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TransferToTranID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[WriteOffAmt] [money] NULL,
[sys_CreateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_CreateTS] [datetime] NULL,
[sys_CreateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_Status] [int] NULL,
[sys_UpdateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_UpdateTS] [datetime] NULL,
[sys_UpdateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__PAC_PacTran] ON [ods].[PAC_PacTran]
GO
