CREATE TABLE [ods].[VTXproducts]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_UpdatedDate] [datetime] NULL,
[ETL_IsDeleted] [bit] NULL,
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvendortype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvendorkey] [numeric] (10, 0) NULL,
[productid] [numeric] (10, 0) NULL,
[producttype] [int] NULL,
[productdescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productdetails2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productdetails3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productdefaultmerchid] [int] NULL,
[productvendorstocknumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvendorcostmethod] [int] NULL,
[productvendorcosttable] [int] NULL,
[productvendorcost] [numeric] (19, 4) NULL,
[productvendorcostrate2] [numeric] (19, 4) NULL,
[productvendorcostrate3] [numeric] (19, 4) NULL,
[productusercostmethod] [int] NULL,
[productusercosttable] [int] NULL,
[productusercost] [numeric] (19, 4) NULL,
[productqty] [float] NULL,
[productunits] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productshipinitzip] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productavailable] [smallint] NULL,
[productdisplaytousers] [smallint] NULL,
[productdisplayorder] [int] NULL,
[producttimeoutdays] [float] NULL,
[productsearchgroups] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[producttaxtable] [int] NULL,
[productsplittable] [int] NULL,
[productinitdate] [datetime2] (6) NULL,
[productlastupdatewhen] [datetime2] (6) NULL,
[productlastupdatewho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[producttaxpoint] [smallint] NULL,
[productspecialprocessing] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productteaserstoryid] [numeric] (10, 0) NULL,
[productinfostoryid] [numeric] (10, 0) NULL,
[productvolumediscountcategory] [smallint] NULL,
[prodvolumediscountsubcategory] [smallint] NULL,
[prodvolumediscountdiscntcode] [int] NULL,
[prodvolumediscountdiscntentry] [int] NULL,
[prodoutofstockfullfillprocess] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodinstockfullfillmentprocess] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodcustomvolumediscountinplay] [smallint] NULL,
[prodsubscriptfreetimedatepart] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodsubscripfreetimeincrement] [int] NULL,
[prodincrementloyaltypntprogram] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodloyaltypntprogramincrement] [nvarchar] (192) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productcustomshipserveinplay] [smallint] NULL,
[productdetails4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productonsalediscount] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productshipinitstate] [smallint] NULL,
[productshipinitcounty] [int] NULL,
[productcurrentstockquantity] [numeric] (10, 0) NULL,
[productlowstocklevelquantity] [numeric] (10, 0) NULL,
[productdetails] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvalidshippingoptions] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productaddadvsecroles] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productadduserretrcodes] [nvarchar] (192) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productglcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productinactive] [smallint] NULL,
[refundaltpaymenttype] [numeric] (10, 0) NULL,
[productentityid] [smallint] NULL,
[productdisplaydescription] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[channel1merchid] [int] NULL,
[channel2merchid] [int] NULL,
[channel3merchid] [int] NULL,
[channel4merchid] [int] NULL,
[channel5merchid] [int] NULL,
[id] [numeric] (20, 0) NULL,
[client_id] [numeric] (10, 0) NULL,
[settlement_code_id] [numeric] (18, 0) NULL
)
GO
ALTER TABLE [ods].[VTXproducts] ADD CONSTRAINT [PK__VTXprodu__7EF6BFCDAC37CDC1] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
