CREATE TABLE [ods].[PAC_Account]
(
[AccountDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[AccountID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AccountName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountTypeCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountTypeCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountTypeCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountTypeCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOnlineLockFlag] [bit] NULL,
[Announcement] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountOrgImageID] [uniqueidentifier] NULL,
[AccountOrgName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountOrgURL] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountOrgComments] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountOrgIndustryCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgIndustryCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgIndustryCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgIndustryCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgTypeCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgTypeCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgTypeCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountOrgTypeCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundBillAddrCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundBillAddrCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundBillAddrCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundBillAddrCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundMailAddrCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundMailAddrCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundMailAddrCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FundMailAddrCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketBillAddrCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketBillAddrCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketBillAddrCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketBillAddrCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketMailAddrCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketMailAddrCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketMailAddrCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TicketMailAddrCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HouseholdIncCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HouseholdIncCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HouseholdIncCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HouseholdIncCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredContactMethodCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredContactMethodCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredContactMethodCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredContactMethodCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredEmail] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredLanguageCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredPhoneTypeCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredPhoneTypeCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredPhoneTypeCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PreferredPhoneTypeCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SourceCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[StatusCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PrimaryContactID] [uniqueidentifier] NULL,
[PrimaryFundRepUserID] [bigint] NULL,
[PrimaryGeneralRepUserID] [bigint] NULL,
[PrimaryTicketingRepUserID] [bigint] NULL,
[OriginationUser] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginationTime] [datetime] NULL,
[sys_CreateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_CreateTS] [datetime] NULL,
[sys_CreateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_Status] [int] NULL,
[sys_UpdateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_UpdateTS] [datetime] NULL,
[sys_UpdateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__PAC_Account] ON [ods].[PAC_Account]
GO
