CREATE TABLE [ods].[VTXtixeventzoneseatgroups]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_UpdatedDate] [datetime] NULL,
[ETL_IsDeleted] [bit] NULL,
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventid] [numeric] (10, 0) NULL,
[tixeventzoneid] [smallint] NULL,
[tixseatgroupid] [int] NULL,
[tixseatgroupdesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgrouptype] [smallint] NULL,
[tixseatgroupdisplayorder] [smallint] NULL,
[tixseatgroupparentgroup] [int] NULL,
[tixseatgroupgrandparent] [int] NULL,
[tixseatgroupgreatgrandparent] [int] NULL,
[tixseatgrouplevelsfromevent] [smallint] NULL,
[tixseatgrouptotalingroup] [numeric] (10, 0) NULL,
[tixseatgrouptotalonsale] [numeric] (10, 0) NULL,
[tixseatgrouptotalremaining] [numeric] (10, 0) NULL,
[tixseatgrouptotalkills] [numeric] (10, 0) NULL,
[tixseatgrouptotalcomps] [numeric] (10, 0) NULL,
[tixseatgrouptotalonhold] [numeric] (10, 0) NULL,
[tixseatgrouptotalsold] [numeric] (10, 0) NULL,
[tixseatgrouptotalnonallocsold] [numeric] (10, 0) NULL,
[tixseatgrouptotalprinted] [numeric] (10, 0) NULL,
[tixseatgrouppricelevel] [numeric] (10, 0) NULL,
[tixseatgroupsalepriority] [numeric] (10, 0) NULL,
[tixseatgroupmultiavailstatflag] [smallint] NULL,
[tixseatgroupprimaryspeccode] [int] NULL,
[tixseatgrouptotalnonallocpaid] [numeric] (10, 0) NULL,
[tixseatgrouptotalpaid] [numeric] (10, 0) NULL,
[tixseatgroupnonallocpaidbucks] [numeric] (19, 4) NULL,
[tixseatgroupnonallocsoldbucks] [numeric] (19, 4) NULL,
[tixseatgrouppaidbucks] [numeric] (19, 4) NULL,
[tixseatgroupsoldbucks] [numeric] (19, 4) NULL,
[tixseatgroupnonallocpaidvalue] [numeric] (19, 4) NULL,
[tixseatgroupnonallocsoldvalue] [numeric] (19, 4) NULL,
[tixseatgrouppaidvalue] [numeric] (19, 4) NULL,
[tixseatgroupsoldvalue] [numeric] (19, 4) NULL,
[tixseatgroupsoldtod8] [numeric] (19, 4) NULL,
[tixseatgroupnonallocsoldtod8] [numeric] (19, 4) NULL,
[tixseatgroupcompsvalue] [numeric] (19, 4) NULL,
[tixseatgroupflashmovieframeid] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgroupcompassright] [int] NULL,
[tixseatgroupcompassleft] [int] NULL,
[tixseatgroupcompassup] [int] NULL,
[tixseatgroupcompassdown] [int] NULL,
[tixseatgrouplevelstoseats] [smallint] NULL,
[tixeventzoneseatgrouplastupd] [datetime2] (6) NULL,
[tixseatgroupseatrequestgroup] [int] NULL,
[tixseatgrouptotalnonalloccomp] [numeric] (10, 0) NULL,
[tixseatgroupnonalloccompsvalue] [numeric] (19, 4) NULL,
[tixseatgroupsaleorder] [numeric] (10, 0) NULL,
[tixseatgrouptotalingroup_nona] [numeric] (10, 0) NULL,
[tixseatgrouptotalonsale_nona] [numeric] (10, 0) NULL,
[tixseatgrouptotalremain_nona] [numeric] (10, 0) NULL,
[tixseatgrouptotalonhold_nona] [numeric] (10, 0) NULL,
[tixseatgrouptotalkills_nona] [numeric] (10, 0) NULL,
[tixseatgrouptotalallocations] [numeric] (10, 0) NULL,
[tixseatgrouptotalconsign] [numeric] (10, 0) NULL,
[tixseatgroupconsignprice] [numeric] (19, 4) NULL,
[tixseatgroupprintdesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgroupflashmovietype] [smallint] NULL,
[tixseatgroupavailableforweb] [smallint] NULL,
[tixseatgroupcenterindicator] [smallint] NULL,
[tixseatgroupdisplayasga] [smallint] NULL,
[tixseatgroupaddlinfo] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgroupgaseatdescription] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ods].[VTXtixeventzoneseatgroups] ADD CONSTRAINT [PK__VTXtixev__7EF6BFCD8933484C] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
CREATE NONCLUSTERED INDEX [idx_tixeventidtixeventzoneidtixseatgroupid] ON [ods].[VTXtixeventzoneseatgroups] ([tixeventid], [tixeventzoneid], [tixseatgroupid])
GO
CREATE NONCLUSTERED INDEX [IDX_VTXtixeventzoneseatgroups_tixseatgroupid_tixeventid_tixeventzoneid] ON [ods].[VTXtixeventzoneseatgroups] ([tixseatgroupid], [tixeventid], [tixeventzoneid])
GO
CREATE NONCLUSTERED INDEX [IX_tixseatgroupsaleorder] ON [ods].[VTXtixeventzoneseatgroups] ([tixseatgroupsaleorder])
GO
