CREATE TABLE [ods].[VTXordergroups]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_UpdatedDate] [datetime] NULL,
[ETL_IsDeleted] [bit] NULL,
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroup] [numeric] (10, 0) NULL,
[ordergroupsegregationcode] [smallint] NULL,
[ordergrouppaymentmode] [smallint] NULL,
[ordergroupshipservechargemode] [smallint] NULL,
[ordergroupmasterorderid] [numeric] (10, 0) NULL,
[ordergroupinituser] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupenteredby] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouporiginaltotal] [numeric] (19, 4) NULL,
[ordergroupgrandtotal] [numeric] (19, 4) NULL,
[ordergrouptotaldiscounts] [numeric] (19, 4) NULL,
[ordergrouptotaltax] [numeric] (19, 4) NULL,
[ordergroupshippingtotal] [numeric] (19, 4) NULL,
[ordergroupshippingdiscounts] [numeric] (19, 4) NULL,
[ordergroupshippingtax] [numeric] (19, 4) NULL,
[ordergroupservicechgtotal] [numeric] (19, 4) NULL,
[ordergroupservicechgdiscount] [numeric] (19, 4) NULL,
[ordergroupservicechgtax] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentsreq] [numeric] (19, 4) NULL,
[ordergrouptotalaltpayments] [numeric] (19, 4) NULL,
[ordergrouprelatedestabtype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouprelatedestabkey] [numeric] (10, 0) NULL,
[ordergroupordertype] [smallint] NULL,
[ordergroupsingleormultiuser] [smallint] NULL,
[ordergroupshippingdestmode] [smallint] NULL,
[ordergrouprelatedestabrelation] [int] NULL,
[ordergroupshipname] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipaddress1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipaddress2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipcity] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipst] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipcountry] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipzip] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipstatecode] [int] NULL,
[ordergroupshippingzone] [int] NULL,
[ordergroupshippingzoneinvalid] [smallint] NULL,
[usercountycode] [int] NULL,
[ordergroupinitialep] [smallint] NULL,
[ordergroupcheckoutep] [smallint] NULL,
[ordergroupshipcountycode] [int] NULL,
[ordergroupuserid] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupconfirmationnumber] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouptimetoplaceorder] [numeric] (10, 0) NULL,
[ordergroupbottomlineorigtotal] [numeric] (19, 4) NULL,
[ordergroupbottomlinegrandtotal] [numeric] (19, 4) NULL,
[ordergroupbottomlineactivtotal] [numeric] (19, 4) NULL,
[ordergroupbottomlinetotaltax] [numeric] (19, 4) NULL,
[ordergroupbottomlinetotaldisc] [numeric] (19, 4) NULL,
[ordergroupactivetotal] [numeric] (19, 4) NULL,
[ordergroupshippingactivetotal] [numeric] (19, 4) NULL,
[ordergroupservicechgactivtotal] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentscleared] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentsonhold] [numeric] (19, 4) NULL,
[ordergrouptotalpaymentsinqueue] [numeric] (19, 4) NULL,
[ordergrouppaymentbalance] [numeric] (19, 4) NULL,
[ordergroupdate] [datetime2] (6) NULL,
[ordergroupclosedondate] [datetime2] (6) NULL,
[ordergroupstatus] [smallint] NULL,
[ordergrouptimetocompleteorder] [numeric] (10, 0) NULL,
[ordergroupclosed] [smallint] NULL,
[ordergrouplastupdated] [datetime2] (6) NULL,
[ordergroupinvoicenumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[commentid] [numeric] (10, 0) NULL,
[ordergroupoutletid] [numeric] (10, 0) NULL,
[ordergrouppaymentstatus] [smallint] NULL,
[eticketemail] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerid] [numeric] (38, 10) NULL,
[willcallcode] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addressid] [numeric] (10, 0) NULL,
[willcallname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [numeric] (10, 0) NULL,
[tickets_ever_in_fs] [smallint] NULL,
[convertfsunpaid] [smallint] NULL,
[tags] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouppaymentbypass] [smallint] NULL
)
GO
ALTER TABLE [ods].[VTXordergroups] ADD CONSTRAINT [PK__VTXorder__7EF6BFCDC921D32A] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
CREATE NONCLUSTERED INDEX [IDX_Customerid] ON [ods].[VTXordergroups] ([customerid])
GO
CREATE NONCLUSTERED INDEX [IX_ordergroup] ON [ods].[VTXordergroups] ([ordergroup])
GO
CREATE NONCLUSTERED INDEX [nci_wi_VTXordergroups_FE0C5B2BD9A35C7D1B439834D2AEA6DE] ON [ods].[VTXordergroups] ([ordergroupdate]) INCLUDE ([customerid])
GO
