CREATE TABLE [ods].[PAC_PacTranPayment]
(
[OrganizationID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PacTranID] [bigint] NOT NULL,
[PacTranPaymentID] [int] NOT NULL,
[AccountDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AccountID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Institution] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAccountNickName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoutingNumber] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAccountNumber] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAccountHolderFirstName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAccountHolderLastName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpirationMonth] [int] NULL,
[ExpirationYear] [int] NULL,
[IsAutoPay] [bit] NULL,
[IsBankAccountPreferred] [bit] NULL,
[IsCreditCardPreferred] [int] NULL,
[LastUsed] [datetime] NULL,
[NameOnCard] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditCardNickName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditCardNumber] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[channelId] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gateway] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gatewayTransactionId] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gatewayAvsResponse] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gatewayCvnResponse] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gatewayResponse] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gatewayAuthorizationCode] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressCareOf] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress1] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress2] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddress3] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressCity] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressCounty] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressState] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressZipCode] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingAddressCountry] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RegionCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RegionCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RegionCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DistributionTypeCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DistributionTypeCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DistributionTypeCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DistributionTypeCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DocumentNbr] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MerchantID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PayCodeID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[Payment] [money] NULL,
[PaymentCurrencyCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentCurrencyCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentCurrencyCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentCurrencyCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentDate] [datetime] NULL,
[PaymentTypeCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentTypeCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentTypeCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PaymentTypeCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[Reference] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SettlementAmt] [money] NULL,
[SettlementBatch] [bigint] NULL,
[SettlementDate] [datetime] NULL,
[TenderAmt] [money] NULL,
[TerminalID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EntryMethodCodeDbID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EntryMethodCodeType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EntryMethodCodeSubtype] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EntryMethodCode] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[sys_CreateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_CreateTS] [datetime] NULL,
[sys_CreateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_Status] [int] NULL,
[sys_UpdateIP] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sys_UpdateTS] [datetime] NULL,
[sys_UpdateUser] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__PAC_PacTranPayment] ON [ods].[PAC_PacTranPayment]
GO
