CREATE TABLE [src].[VTXoffers]
(
[ETL_ID] [int] NOT NULL,
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[id] [numeric] (20, 0) NULL,
[lookup] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[display_date] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sort_date] [datetime2] (6) NULL,
[promotion_code] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[on_sale_date] [datetime2] (6) NULL,
[off_sale_date] [datetime2] (6) NULL,
[ae_user_id] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ae_role_id] [numeric] (20, 0) NULL,
[use_user_ssc] [smallint] NULL,
[min_qty] [numeric] (10, 0) NULL,
[max_qty] [numeric] (10, 0) NULL,
[customer_list_id] [numeric] (20, 0) NULL,
[pref_fee_target] [numeric] (20, 0) NULL,
[published] [smallint] NULL,
[list_online] [smallint] NULL,
[is_draft] [smallint] NULL,
[image] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [numeric] (10, 0) NULL,
[allow_public_seat_change] [smallint] NULL,
[require_contiguous_seats] [smallint] NULL,
[allow_empty_single_seats] [smallint] NULL,
[additional_info1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[additional_info2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_restriction_count] [numeric] (10, 0) NULL,
[has_account_restriction] [smallint] NULL,
[has_pass_code_restriction] [smallint] NULL,
[has_sign_in_restriction] [smallint] NULL,
[system_type] [smallint] NULL,
[timer_profile_id] [int] NULL,
[default_restrict_transfer] [smallint] NULL,
[default_restrict_resale] [smallint] NULL,
[default_waive_first_seller_fee] [smallint] NULL,
[osearch] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fs_redirect] [smallint] NULL,
[offerlabel] [smallint] NULL,
[version] [numeric] (18, 0) NULL,
[tags] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[offer_image_id] [numeric] (18, 0) NULL,
[mobile_image_id] [numeric] (18, 0) NULL,
[allow_additional_donation_ots] [smallint] NULL
)
GO
