CREATE TABLE [src].[VTXestablishments]
(
[ETL_ID] [int] NOT NULL,
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenttype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentkey] [numeric] (10, 0) NULL,
[establishmentfullname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentdescription] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentcompanyname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaffilation] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentownership] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaddress1] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaddress2] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaddress3] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentcity] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentstate] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentstatecode] [smallint] NULL,
[establishmentzip] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentcountry] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentlocationcode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentdirectline] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenttollfreeinstate] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenttollfreeoutstate] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentexecofficenumber] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentpublicemail] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenthomepage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsitecreated] [datetime2] (6) NULL,
[establishmentinitdate] [datetime2] (6) NULL,
[establishmentsuggestedby] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsuggestedbystring] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentlastupdatewhen] [datetime2] (6) NULL,
[establishmentlastupdatewho] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentquicknavcode] [numeric] (10, 0) NULL,
[establishmentremoteadmincode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannerfilename] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannerorigfile] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbanneruploadwhen] [datetime2] (6) NULL,
[establishmentbanneruploadwho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannersizebytes] [numeric] (10, 0) NULL,
[establishmentbannersizewidth] [numeric] (10, 0) NULL,
[establishmentbannersizeheight] [numeric] (10, 0) NULL,
[establishmentbannerapproved] [smallint] NULL,
[establishmentbannerapprovewhen] [datetime2] (6) NULL,
[establishmentbannerapprovewho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannerswap] [smallint] NULL,
[establishmentlinkexchange] [smallint] NULL,
[establishmentbannerweightperc] [float] NULL,
[establishmentbannerweightshar] [float] NULL,
[establishmentbannertimemult] [float] NULL,
[establishmentevtschedstatus] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedlimitlist] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedsysname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedmaxdb1rec] [numeric] (10, 0) NULL,
[establishmentevtschedmaxdb2rec] [numeric] (10, 0) NULL,
[establishmentevtscheddb1name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1item] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2item] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1refint] [smallint] NULL,
[establishmentevtscheddb2refint] [smallint] NULL,
[establishmentevtschedeventname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedeventitem] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1mode] [int] NULL,
[establishmentevtscheddb2mode] [int] NULL,
[establishmentevtscheddefltdb1] [smallint] NULL,
[establishmentevtscheddb1type] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1key] [numeric] (10, 0) NULL,
[establishmentevtscheddb1id] [numeric] (10, 0) NULL,
[establishmentevtscheddb2type] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2key] [numeric] (10, 0) NULL,
[establishmentevtscheddb2id] [numeric] (10, 0) NULL,
[establishmentevtscheddb2pname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2pitem] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedcalline1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedcalline2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedcalline3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedmmmaxbyte] [numeric] (10, 0) NULL,
[establishmentevtschedmaxestrec] [numeric] (10, 0) NULL,
[establishmentevtscheddefltdays] [numeric] (10, 0) NULL,
[establishmentevtschedlinkcntrl] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentprimarytype] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecondarytype] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfanclubstatus] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfaxnumber] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentvthomepage] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfanclubnewmembers] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentvtphotospage] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmententrypoint] [smallint] NULL,
[establishmentcountycode] [int] NULL,
[usercountycode] [int] NULL,
[establishmentbannernotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschednotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfanclubnewmemberm] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentnotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [numeric] (10, 0) NULL,
[spacebisonenabled] [smallint] NULL
)
GO
