CREATE TABLE [src].[VTXtixeventzones]
(
[ETL_ID] [int] NOT NULL,
[ETL_CreatedDate] [datetime] NOT NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventid] [numeric] (10, 0) NULL,
[tixeventzoneid] [smallint] NULL,
[tixeventonsale] [datetime2] (6) NULL,
[tixeventtourid] [int] NULL,
[tixeventinitdate] [datetime2] (6) NULL,
[tixeventlastupdwhen] [datetime2] (6) NULL,
[tixeventbuiltfromseatmap] [numeric] (10, 0) NULL,
[tixeventseatmaplocked] [smallint] NULL,
[tixeventstatus] [smallint] NULL,
[tixeventtopseatgrouptype] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventlastupdatewho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventticketformat] [smallint] NULL,
[tixeventtotalseats] [numeric] (10, 0) NULL,
[tixeventtotalonsale] [numeric] (10, 0) NULL,
[tixeventtotalremaining] [numeric] (10, 0) NULL,
[tixeventtotalkills] [numeric] (10, 0) NULL,
[tixeventtotalcomps] [numeric] (10, 0) NULL,
[tixeventtotalonhold] [numeric] (10, 0) NULL,
[tixeventtotalsold] [numeric] (10, 0) NULL,
[tixeventtotalnonallocsold] [numeric] (10, 0) NULL,
[tixeventtotalprinted] [numeric] (10, 0) NULL,
[tixeventzonedesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzonedispord] [smallint] NULL,
[tixeventzonetype] [int] NULL,
[tixeventinventorysecurityincl] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventinventorysearchinclude] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneonsale] [smallint] NULL,
[tixeventzonereadyforsale] [smallint] NULL,
[tixeventzonenexteventid] [numeric] (10, 0) NULL,
[tixeventzonepreveventid] [numeric] (10, 0) NULL,
[tixeventzonenextzoneid] [smallint] NULL,
[tixeventzoneprevzoneid] [smallint] NULL,
[evtschedeventdb1estabtype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[evtschedeventdb1estabkey] [numeric] (10, 0) NULL,
[tixeventtotalpaid] [numeric] (10, 0) NULL,
[tixeventtotalnonallocpaid] [numeric] (10, 0) NULL,
[tixeventtotalsoldbucks] [numeric] (19, 4) NULL,
[tixeventtotalnonallocsoldbucks] [numeric] (19, 4) NULL,
[tixeventtotalpaidbucks] [numeric] (19, 4) NULL,
[tixeventtotalnonallocpaidbucks] [numeric] (19, 4) NULL,
[tixeventtotalsoldtod8] [numeric] (19, 4) NULL,
[tixeventtotalnonallocsoldtod8] [numeric] (19, 4) NULL,
[tixeventtotalsoldvalue] [numeric] (19, 4) NULL,
[tixeventtotalpaidvalue] [numeric] (19, 4) NULL,
[tixeventtotalnonallocsoldvalue] [numeric] (19, 4) NULL,
[tixeventtotalnonallocpaidvalue] [numeric] (19, 4) NULL,
[tixeventtotalcompsvalue] [numeric] (19, 4) NULL,
[tixeventzonefullauditactive] [smallint] NULL,
[tixeventflashmovieid] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixevtznproductvendortype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixevtznproductvendorkey] [numeric] (10, 0) NULL,
[tixevtznproductid] [numeric] (10, 0) NULL,
[tixevtznavailabilitymsg] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneallowsingles] [smallint] NULL,
[tixevtznseatrequestseatgroup] [int] NULL,
[tixeventtotalnonalloccomp] [numeric] (10, 0) NULL,
[tixeventtotalnonalloccompvalue] [numeric] (19, 4) NULL,
[tixevtznallowseatrequests] [smallint] NULL,
[tixevtznseatrequestdate] [datetime2] (6) NULL,
[tixeventzonenexthistoryid] [int] NULL,
[tixeventpricechartlocked] [smallint] NULL,
[tixeventeventlocked] [smallint] NULL,
[tixeventzonenexterrorcheckid] [smallint] NULL,
[tixeventzonerenewablefornextyr] [smallint] NULL,
[tixeventoffsale] [datetime2] (6) NULL,
[tixeventzonesectionpriormulti] [smallint] NULL,
[tixevent_nba_rowsizefactor] [smallint] NULL,
[tixevtznrunbackgroundintegchk] [smallint] NULL,
[tixevtznseatrequestsonsale] [smallint] NULL,
[tixevtznlastsccssfulintegchkd8] [datetime2] (6) NULL,
[tixeventzonedisplay5nba1] [numeric] (10, 0) NULL,
[tixeventzonedisplay5nba2] [numeric] (10, 0) NULL,
[tixeventzonedisplay5nba3] [numeric] (10, 0) NULL,
[tixeventzonedisplay5nba4] [numeric] (10, 0) NULL,
[tixeventtotalseats_nona] [numeric] (10, 0) NULL,
[tixeventtotalonsale_nona] [numeric] (10, 0) NULL,
[tixeventtotalremaining_nona] [numeric] (10, 0) NULL,
[tixeventtotalonhold_nona] [numeric] (10, 0) NULL,
[tixeventtotalkills_nona] [numeric] (10, 0) NULL,
[tixeventtotalallocations] [numeric] (10, 0) NULL,
[tixevtznglcode] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventtotalconsign] [numeric] (10, 0) NULL,
[tixeventconsignprice] [numeric] (19, 4) NULL,
[tixeventzoneavailableforweb] [smallint] NULL,
[tixeventzoneusestopcard] [smallint] NULL,
[tixeventzoneiscanceled] [smallint] NULL,
[tixeventzonecancellationdate] [datetime2] (6) NULL,
[tixeventzonecancellationreason] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[display_in_reports] [smallint] NULL,
[tixeventzoneeticketline1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline6] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixtransferfeeenabled] [numeric] (38, 10) NULL,
[tixeventzoneallowtixforwarding] [smallint] NULL,
[tixeventzoneallowonlinepayment] [smallint] NULL,
[ac_lasthistoryptr] [numeric] (20, 0) NULL,
[ac_exportzone] [smallint] NULL,
[product_id] [numeric] (20, 0) NULL,
[venue_map_id] [numeric] (20, 0) NULL,
[is_published] [smallint] NULL,
[client_id] [numeric] (10, 0) NULL,
[event_owner_id] [numeric] (10, 0) NULL,
[accesscontrolenddatetime] [datetime2] (6) NULL,
[accesscontrolstartdatetime] [datetime2] (6) NULL,
[enableaccesscontrol] [smallint] NULL,
[tixeventzoneversion] [numeric] (18, 0) NULL,
[tixeventzonemaxentry] [smallint] NULL,
[tixeventzonemaxperday] [smallint] NULL,
[tixeventzoneentryexit] [smallint] NULL,
[stadis_active] [smallint] NULL,
[stadis_exported] [smallint] NULL,
[stadis_lasthistoryptr] [numeric] (20, 0) NULL,
[sales_restrict] [smallint] NULL,
[convertfsunpaid] [smallint] NULL,
[seatmap_image_id] [numeric] (18, 0) NULL,
[seatmap_image_mode] [smallint] NULL,
[enable_paper_conversion] [smallint] NULL,
[waive_paper_conversion_fee] [smallint] NULL,
[salespricechartversion] [numeric] (18, 0) NULL,
[printpricechartversion] [numeric] (18, 0) NULL,
[textpricechartversion] [numeric] (18, 0) NULL,
[single_forward] [int] NULL
)
GO
