CREATE USER [ctaylor] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[ctaylor]
GO
GRANT CREATE FUNCTION TO [ctaylor]
GRANT CREATE PROCEDURE TO [ctaylor]
GRANT CREATE TABLE TO [ctaylor]
GRANT CREATE VIEW TO [ctaylor]
