CREATE SCHEMA [ods]
AUTHORIZATION [svcETL]
GO
GRANT SELECT ON SCHEMA:: [ods] TO [ajoyce]
GO
GRANT SELECT ON SCHEMA:: [ods] TO [ctaylor]
GO
GRANT ALTER ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT DELETE ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT INSERT ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT SELECT ON SCHEMA:: [ods] TO [db_apiETL]
GO
GRANT UPDATE ON SCHEMA:: [ods] TO [db_apiETL]
GO
