CREATE SCHEMA [ro]
AUTHORIZATION [dbo]
GO
GRANT EXECUTE ON SCHEMA:: [ro] TO [CI_ClientAccess]
GO
GRANT SELECT ON SCHEMA:: [ro] TO [CI_ClientAccess]
GO
GRANT EXECUTE ON SCHEMA:: [ro] TO [CI_ClientWriter]
GO
GRANT SELECT ON SCHEMA:: [ro] TO [CI_ClientWriter]
GO
GRANT REFERENCES ON SCHEMA:: [ro] TO [CI_ClientWriter]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [ro] TO [CI_ClientWriter]
GO
